var vmPortalState={profile:null,membership:null,portal:null,assignments:[],attempts:[]};
function vmPortalEsc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(ch){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[ch];});}
function vmPortalDate(value){if(!value)return '';return new Date(value).toLocaleString('vi-VN',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit',year:'numeric'});}
function vmPortalSlug(){return (new URLSearchParams(location.search).get('portal')||'').trim().toLowerCase();}
function vmPortalView(view){['Exams','Results','Manage'].forEach(function(name){var panel=document.getElementById('portalPanel'+name);if(panel)panel.hidden=name.toLowerCase()!==view;});document.querySelectorAll('.portal-nav [data-view]').forEach(function(btn){btn.classList.toggle('active',btn.dataset.view===view);});if(location.hash!=='#'+view)history.replaceState({},'',location.pathname+location.search+'#'+view);}
function vmPortalExamStatus(assignment){var now=Date.now(),start=assignment.available_from?new Date(assignment.available_from).getTime():null,end=assignment.available_until?new Date(assignment.available_until).getTime():null;if(!assignment.published)return{key:'closed',label:'Chưa công bố'};if(start&&start>now)return{key:'upcoming',label:'Mở '+vmPortalDate(assignment.available_from)};if(end&&end<now)return{key:'closed',label:'Đã kết thúc'};return{key:'open',label:'Đang mở'};}
async function vmPortalLoad(){
  if(!daKetNoi())return;
  var session=await sb.auth.getSession();
  var slug=vmPortalSlug();
  if(!session.data.session){location.href='dang-nhap?portal='+encodeURIComponent(slug);return;}
  var uid=session.data.session.user.id;
  var profileResponse=await sb.from('profiles').select('id,role,username,full_name').eq('id',uid).single();
  if(profileResponse.error||!profileResponse.data){location.href='dang-nhap?portal='+encodeURIComponent(slug);return;}
  vmPortalState.profile=profileResponse.data;
  var membershipResponse=await sb.from('exam_portal_members').select('member_role,portal_only,portal:exam_portals!inner(id,slug,name,short_name,description,logo_path,support_text,is_active,brand:brand_templates('+VM_BRAND_COLUMNS+'))').eq('user_id',uid).eq('portal.slug',slug).maybeSingle();
  var membership=membershipResponse.data;
  if((!membership||!membership.portal)&&profileResponse.data.role==='admin'){
    var portalResponse=await sb.from('exam_portals').select('id,slug,name,short_name,description,logo_path,support_text,is_active,brand:brand_templates('+VM_BRAND_COLUMNS+')').eq('slug',slug).maybeSingle();
    if(portalResponse.data)membership={member_role:'owner',portal_only:false,portal:portalResponse.data};
  }
  if(!membership||!membership.portal||!membership.portal.is_active){document.getElementById('portalName').textContent='Không có quyền truy cập';document.getElementById('portalDescription').textContent='Tài khoản này không thuộc cổng thi được yêu cầu.';document.getElementById('portalExamList').innerHTML='<div class="card portal-empty">Hãy kiểm tra lại tên đăng nhập hoặc liên hệ người phụ trách.</div>';return;}
  vmPortalState.membership=membership;vmPortalState.portal=membership.portal;
  if(membership.portal.brand&&typeof vmApDungThuongHieu==='function')vmApDungThuongHieu(membership.portal.brand);
  document.title=(membership.portal.short_name||membership.portal.name)+' — Cổng thi';document.getElementById('portalName').textContent=membership.portal.name;document.getElementById('portalShortName').textContent=membership.portal.short_name||membership.portal.name;document.getElementById('portalDescription').textContent=membership.portal.description||'Kỳ thi và kết quả được quản lý trong một khu vực riêng.';document.getElementById('portalUser').textContent=profileResponse.data.full_name||profileResponse.data.username||'Học sinh';document.getElementById('portalHome').href='thi?portal='+encodeURIComponent(slug);document.getElementById('portalNow').textContent=new Date().toLocaleDateString('vi-VN',{weekday:'long',day:'2-digit',month:'2-digit'});
  var logo=membership.portal.logo_path||(membership.portal.brand&&typeof vmUrlLogoThuongHieu==='function'?vmUrlLogoThuongHieu(membership.portal.brand):'');if(logo)document.getElementById('portalLogo').src=logo;
  var canManage=['owner','manager'].indexOf(membership.member_role)!==-1||profileResponse.data.role==='admin';document.getElementById('portalManageTab').hidden=!canManage;document.getElementById('portalAdminLink').hidden=profileResponse.data.role!=='admin';
  var assigned=await sb.from('exam_portal_exams').select('portal_id,exam_id,published,show_result,available_from,available_until,sort,exam:exams(id,title,duration_minutes,opens_at,closes_at,de_type,exam_questions(count))').eq('portal_id',membership.portal.id).order('sort').order('available_from',{ascending:true,nullsFirst:true});
  if(assigned.error){document.getElementById('portalExamList').innerHTML='<div class="card portal-empty">Không tải được danh sách kỳ thi. Vui lòng thử lại sau.</div>';return;}
  vmPortalState.assignments=assigned.data||[];
  var examIds=vmPortalState.assignments.map(function(item){return item.exam_id;});
  if(examIds.length){var attempts=await sb.from('attempts').select('id,exam_id,student_id,started_at,submitted_at,score,correct_n,total_n').in('exam_id',examIds).eq('student_id',uid).order('started_at',{ascending:false});vmPortalState.attempts=attempts.data||[];}
  vmPortalRenderExams();vmPortalRenderResults();if(canManage)await vmPortalRenderManage();
  var initial=(location.hash||'#exams').slice(1);if(['exams','results','manage'].indexOf(initial)===-1||initial==='manage'&&!canManage)initial='exams';vmPortalView(initial);
}
function vmPortalRenderExams(){var list=document.getElementById('portalExamList');var rows=vmPortalState.assignments.filter(function(item){return item.exam;});document.getElementById('portalOpenCount').textContent=rows.filter(function(item){return vmPortalExamStatus(item).key==='open';}).length;var done=vmPortalState.attempts.filter(function(item){return item.submitted_at;});document.getElementById('portalDoneCount').textContent=done.length;var scores=done.map(function(item){return Number(item.score);}).filter(Number.isFinite);document.getElementById('portalBestScore').textContent=scores.length?Math.max.apply(null,scores).toFixed(1):'—';if(!rows.length){list.innerHTML='<div class="card portal-empty"><b>Chưa có kỳ thi được giao</b><br>Đề mới sẽ xuất hiện tại đây ngay khi người phụ trách công bố.</div>';return;}list.innerHTML=rows.map(function(item){var exam=item.exam,status=vmPortalExamStatus(item),count=exam.exam_questions&&exam.exam_questions[0]?exam.exam_questions[0].count:0,latest=vmPortalState.attempts.find(function(a){return a.exam_id===exam.id;}),action=status.key==='open'?'<a class="btn btn-primary btn-sm" href="luyen-de?portal='+encodeURIComponent(vmPortalState.portal.slug)+'&exam_id='+encodeURIComponent(exam.id)+'">'+(latest&&!latest.submitted_at?'Tiếp tục làm':'Bắt đầu thi')+'</a>':'<button class="btn btn-secondary btn-sm" disabled>'+vmPortalEsc(status.label)+'</button>';return '<article class="card portal-exam"><div><h3>'+vmPortalEsc(exam.title)+'</h3><div class="portal-meta"><span class="portal-chip '+status.key+'">'+vmPortalEsc(status.label)+'</span><span class="portal-chip">⏱ '+Number(exam.duration_minutes||0)+' phút</span>'+(count?'<span class="portal-chip">'+count+' câu</span>':'')+(item.available_until?'<span class="portal-chip">Hạn '+vmPortalEsc(vmPortalDate(item.available_until))+'</span>':'')+'</div></div>'+action+'</article>';}).join('');}
function vmPortalRenderResults(){var box=document.getElementById('portalResultList'),showMap={};vmPortalState.assignments.forEach(function(item){showMap[item.exam_id]=item;});var done=vmPortalState.attempts.filter(function(item){return item.submitted_at&&showMap[item.exam_id]&&showMap[item.exam_id].show_result;});if(!done.length){box.innerHTML='<div class="portal-empty">Chưa có kết quả được công bố.</div>';return;}var names={};vmPortalState.assignments.forEach(function(item){if(item.exam)names[item.exam_id]=item.exam.title;});box.innerHTML='<table class="portal-table"><thead><tr><th>Kỳ thi</th><th>Nộp lúc</th><th>Kết quả</th></tr></thead><tbody>'+done.map(function(item){return '<tr><td><b>'+vmPortalEsc(names[item.exam_id]||'Kỳ thi')+'</b></td><td>'+vmPortalEsc(vmPortalDate(item.submitted_at))+'</td><td><b>'+(item.score==null?'Đã nộp':Number(item.score).toFixed(1))+'</b>'+(item.total_n?'<br><small>'+Number(item.correct_n||0)+'/'+item.total_n+' câu</small>':'')+'</td></tr>';}).join('')+'</tbody></table>';}
async function vmPortalRenderManage(){var content=document.getElementById('portalManageContent');var members=await sb.from('exam_portal_members').select('user_id,member_role,created_at,profile:profiles(id,full_name,username)').eq('portal_id',vmPortalState.portal.id).order('created_at');var memberRows=members.data||[];var examNames={};vmPortalState.assignments.forEach(function(item){if(item.exam)examNames[item.exam_id]=item.exam.title;});var allAttempts=[];var examIds=vmPortalState.assignments.map(function(item){return item.exam_id;});if(examIds.length){var response=await sb.from('attempts').select('id,exam_id,student_id,submitted_at,score,correct_n,total_n').in('exam_id',examIds).order('submitted_at',{ascending:false});allAttempts=response.data||[];}content.innerHTML='<div class="portal-stats"><div class="card portal-stat"><b>'+memberRows.length+'</b><span>Thành viên</span></div><div class="card portal-stat"><b>'+vmPortalState.assignments.length+'</b><span>Đề được giao</span></div><div class="card portal-stat"><b>'+allAttempts.filter(function(a){return a.submitted_at;}).length+'</b><span>Lượt đã nộp</span></div></div><div class="portal-table-wrap"><table class="portal-table"><thead><tr><th>Học sinh</th><th>Vai trò</th><th>Trạng thái gần nhất</th></tr></thead><tbody>'+memberRows.map(function(member){var latest=allAttempts.find(function(a){return a.student_id===member.user_id&&a.submitted_at;}),profile=member.profile||{};return '<tr><td><b>'+vmPortalEsc(profile.full_name||profile.username||member.user_id)+'</b></td><td>'+vmPortalEsc(member.member_role)+'</td><td>'+(latest?vmPortalEsc(examNames[latest.exam_id]||'Đã nộp')+' · '+(latest.score==null?'Đã nộp':Number(latest.score).toFixed(1)):'Chưa có bài nộp')+'</td></tr>';}).join('')+'</tbody></table></div>';}
vmPortalLoad();
