(function(){
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c];});}
  function card(icon,title,detail,href,count){return '<a class="vm-role-action" href="'+href+'"><span class="ic">'+icon+'</span>'+(count!=null?'<span class="count">'+esc(count)+'</span>':'')+'<b>'+esc(title)+'</b><small>'+esc(detail)+'</small></a>';}
  function installDismiss(){var hero=document.getElementById('vmInstallHero');if(!hero)return;if(localStorage.getItem('vm-install-hero-dismissed')==='1'){hero.style.display='none';return;}var b=document.createElement('button');b.type='button';b.className='vm-install-dismiss';b.setAttribute('aria-label','Ẩn gợi ý cài ứng dụng');b.textContent='×';b.onclick=function(){localStorage.setItem('vm-install-hero-dismissed','1');hero.style.display='none';};hero.appendChild(b);}
  async function count(table,configure){try{var q=sb.from(table).select('id',{count:'exact',head:true});q=configure(q);var r=await q;return r.count||0;}catch(e){return 0;}}
  window.vmRoleHomeRender=async function(profile){installDismiss();var box=document.getElementById('vmRoleFocus'),actions=document.getElementById('vmRoleActions'),title=document.getElementById('vmRoleTitle'),sub=document.getElementById('vmRoleSub');if(!box||!profile)return;
    var role=profile.role;
    if(['admin','teacher','assistant'].indexOf(role)!==-1){document.body.classList.add('vm-home-staff');var pending=await count('submissions',function(q){return q.eq('status','submitted');});var classes=(profile.role==='admin')?'Tất cả':(profile.class_students&&profile.class_students.length||'Của tôi');title.textContent='Việc cần ưu tiên';sub.textContent='Đi thẳng vào công việc giảng dạy thường dùng nhất.';actions.innerHTML=card('🏫','Lớp học','Mở ngay lớp và danh sách bài giảng gần nhất.','quan-tri-lop',classes)+card('✍️','Bài chờ chấm','Xử lý bài nộp chưa được phản hồi.','quan-tri-cham-bai',pending)+card('📅','Lịch dạy','Xem buổi dạy, điểm danh và thay đổi lịch.','quan-tri-lich')+card('📚','Nội dung','Soạn tài liệu, đề thi và bài học.','quan-tri-tai-lieu');
    }else{document.body.classList.add('vm-home-student');var classCount=(profile.class_students||[]).length;var mine=await count('submissions',function(q){return q.eq('student_id',profile.id).eq('status','graded');});title.textContent='Hôm nay em học gì?';sub.textContent='Các lối tắt quan trọng nhất được đặt ngay ở đây.';actions.innerHTML=card('▶️','Vào lớp học',classCount?classCount+' lớp đang tham gia':'Chưa được xếp lớp','lop-hoc')+card('📝','Bài đã được chấm','Xem điểm và lời phê mới nhất.','ca-nhan',mine)+card('🧪','Luyện tập','Làm đề được giao và thi thử.','luyen-de')+card('📅','Lịch học','Kiểm tra buổi học sắp tới.','lich-hoc');}
    box.classList.add('is-ready');
  };
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installDismiss);else installDismiss();
})();
