(function (global) {
  'use strict';

  var EPS = 1e-8;
  function add(a,b){return{x:a.x+b.x,y:a.y+b.y};}
  function sub(a,b){return{x:a.x-b.x,y:a.y-b.y};}
  function mul(a,k){return{x:a.x*k,y:a.y*k};}
  function dot(a,b){return a.x*b.x+a.y*b.y;}
  function cross(a,b){return a.x*b.y-a.y*b.x;}
  function length(a){return Math.hypot(a.x,a.y);}
  function distance(a,b){return length(sub(a,b));}
  function midpoint(a,b){return mul(add(a,b),.5);}
  function lineFromPoints(a,b){var d=sub(b,a);return length(d)<EPS?null:{point:a,direction:d};}
  function lineIntersection(a,b){var den=cross(a.direction,b.direction);if(Math.abs(den)<EPS)return null;return add(a.point,mul(a.direction,cross(sub(b.point,a.point),b.direction)/den));}
  function lineCircleIntersections(line,circle){var f=sub(line.point,circle.center),d=line.direction,A=dot(d,d),B=2*dot(f,d),C=dot(f,f)-circle.radius*circle.radius,disc=B*B-4*A*C;if(disc<-EPS)return[];disc=Math.max(0,disc);var s=Math.sqrt(disc);return[add(line.point,mul(d,(-B-s)/(2*A))),add(line.point,mul(d,(-B+s)/(2*A)))];}
  function circleCircleIntersections(a,b){var d=distance(a.center,b.center);if(d> a.radius+b.radius+EPS||d<Math.abs(a.radius-b.radius)-EPS||d<EPS)return[];var x=(a.radius*a.radius-b.radius*b.radius+d*d)/(2*d),h=Math.sqrt(Math.max(0,a.radius*a.radius-x*x)),u=mul(sub(b.center,a.center),1/d),base=add(a.center,mul(u,x)),n={x:-u.y,y:u.x};return[add(base,mul(n,h)),add(base,mul(n,-h))];}
  function angleDegrees(a,b,c){var u=sub(a,b),v=sub(c,b),den=length(u)*length(v);if(den<EPS)return 0;return Math.acos(Math.max(-1,Math.min(1,dot(u,v)/den)))*180/Math.PI;}
  function circumcenter(a,b,c){var d=2*(a.x*(b.y-c.y)+b.x*(c.y-a.y)+c.x*(a.y-b.y));if(Math.abs(d)<EPS)return null;return{x:((a.x*a.x+a.y*a.y)*(b.y-c.y)+(b.x*b.x+b.y*b.y)*(c.y-a.y)+(c.x*c.x+c.y*c.y)*(a.y-b.y))/d,y:((a.x*a.x+a.y*a.y)*(c.x-b.x)+(b.x*b.x+b.y*b.y)*(a.x-c.x)+(c.x*c.x+c.y*c.y)*(b.x-a.x))/d};}

  global.VMToolPlaneMath={add:add,sub:sub,mul:mul,dot:dot,cross:cross,distance:distance,midpoint:midpoint,lineFromPoints:lineFromPoints,lineIntersection:lineIntersection,lineCircleIntersections:lineCircleIntersections,circleCircleIntersections:circleCircleIntersections,angleDegrees:angleDegrees,circumcenter:circumcenter};

  if(typeof document==='undefined')return;
  var canvas=document.getElementById('planeCanvas');if(!canvas)return;
  var ctx=canvas.getContext('2d'),wrap=document.getElementById('planeCanvasWrap'),card=document.getElementById('planeCanvasCard');
  var state={points:[],objects:[],tool:'move',steps:[],polygon:[],origin:{x:0,y:0},scale:70,grid:true,snap:true,axes:true,labels:true,undo:[],redo:[],selected:null};
  var drag={mode:null,id:null,x:0,y:0,start:null},resizeObserver=null,pdfUrl='';
  var colors={line:'#174f8a',accent:'#d78b00',point:'#c34232',derived:'#14805e',fill:'rgba(245,174,48,.12)',grid:'#e7ebef',axis:'#68727d'};
  var toolInfo={
    move:['↖','Di chuyển','Kéo điểm để biến đổi hình; kéo nền để di chuyển khung nhìn.'],point:['●','Tạo điểm','Nhấp vào vùng vẽ để tạo một điểm mới.'],segment:['╱','Đoạn thẳng','Chọn hai điểm làm hai đầu đoạn thẳng.'],line:['⟋','Đường thẳng','Chọn hai điểm để dựng đường thẳng đi qua.'],circle:['○','Đường tròn','Chọn tâm rồi chọn một điểm thuộc đường tròn.'],polygon:['△','Đa giác','Chọn lần lượt các đỉnh, sau đó bấm Khép đa giác.'],midpoint:['◉','Trung điểm','Chọn hai điểm; trung điểm sẽ tự chạy theo.'],intersection:['×','Giao điểm','Chọn hai đường hoặc đường tròn.'],parallel:['∥','Đường song song','Chọn một đường rồi chọn điểm mà đường mới đi qua.'],perpendicular:['⊥','Đường vuông góc','Chọn một đường rồi chọn điểm mà đường mới đi qua.'],angle:['∠','Đo góc','Chọn ba điểm theo thứ tự A – đỉnh – C.'],delete:['⌫','Xóa','Nhấp vào điểm hoặc đối tượng muốn xóa.']
  };
  function $(id){return document.getElementById(id);}
  function clone(data){return JSON.parse(JSON.stringify(data));}
  function snapshot(){state.undo.push(JSON.stringify({points:state.points,objects:state.objects}));if(state.undo.length>60)state.undo.shift();state.redo=[];updateUndo();}
  function restore(raw){var data=JSON.parse(raw);state.points=data.points||[];state.objects=data.objects||[];state.steps=[];state.polygon=[];renderAll();}
  function undo(){if(!state.undo.length)return;state.redo.push(JSON.stringify({points:state.points,objects:state.objects}));restore(state.undo.pop());updateUndo();}
  function redo(){if(!state.redo.length)return;state.undo.push(JSON.stringify({points:state.points,objects:state.objects}));restore(state.redo.pop());updateUndo();}
  function updateUndo(){$('planeUndo').disabled=!state.undo.length;$('planeRedo').disabled=!state.redo.length;}
  function nextLabel(){var used={};state.points.forEach(function(p){used[p.label]=1;});var letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ';for(var i=0;i<letters.length;i++)if(!used[letters[i]])return letters[i];return 'P_'+(state.points.length+1);}
  function id(prefix){return prefix+Date.now().toString(36)+Math.random().toString(36).slice(2,6);}
  function addPoint(pos,options){options=options||{};var p={id:id('p'),label:options.label||nextLabel(),x:pos.x,y:pos.y,kind:options.kind||'free',deps:options.deps||null,choice:options.choice||0};state.points.push(p);return p;}
  function addObject(type,data){var o=Object.assign({id:id('o'),type:type,name:'d'+(state.objects.filter(function(x){return['line','parallel','perpendicular'].indexOf(x.type)>=0;}).length+1)},data||{});state.objects.push(o);return o;}
  function getPoint(idValue,seen){if(idValue&&typeof idValue==='object')idValue=idValue.id;var p=state.points.find(function(x){return x.id===idValue;});if(!p)return null;if(p.kind==='free'||!p.deps)return{x:p.x,y:p.y};seen=seen||{};if(seen[p.id])return{x:p.x,y:p.y};seen[p.id]=1;if(p.kind==='midpoint'){var a=getPoint(p.deps[0],seen),b=getPoint(p.deps[1],seen);return a&&b?midpoint(a,b):null;}if(p.kind==='intersection'){var hits=intersections(getObject(p.deps[0]),getObject(p.deps[1]));return hits[p.choice]||hits[0]||null;}return{x:p.x,y:p.y};}
  function getObject(idValue){return state.objects.find(function(x){return x.id===idValue;});}
  function objectGeometry(o){if(!o)return null;var a,b,base,p;if(o.type==='segment'||o.type==='line'){a=getPoint(o.points[0]);b=getPoint(o.points[1]);return a&&b?{type:o.type,a:a,b:b,line:lineFromPoints(a,b)}:null;}if(o.type==='circle'){a=getPoint(o.points[0]);b=getPoint(o.points[1]);return a&&b?{type:'circle',center:a,radius:distance(a,b)}:null;}if(o.type==='polygon'){var pts=o.points.map(function(pid){return getPoint(pid);}).filter(Boolean);return{type:'polygon',points:pts};}if(o.type==='parallel'||o.type==='perpendicular'){base=objectLine(getObject(o.base));p=getPoint(o.point);if(!base||!p)return null;var d=base.direction;if(o.type==='perpendicular')d={x:-d.y,y:d.x};return{type:o.type,line:{point:p,direction:d},a:p,b:add(p,d)};}if(o.type==='angle'){return{type:'angle',points:o.points.map(function(pid){return getPoint(pid);})};}return null;}
  function objectLine(o){var g=objectGeometry(o);return g&&g.line?g.line:null;}
  function intersections(a,b){var ga=objectGeometry(a),gb=objectGeometry(b);if(!ga||!gb)return[];if(ga.line&&gb.line){var hit=lineIntersection(ga.line,gb.line);return hit?[hit]:[];}if(ga.line&&gb.type==='circle')return lineCircleIntersections(ga.line,gb);if(gb.line&&ga.type==='circle')return lineCircleIntersections(gb.line,ga);if(ga.type==='circle'&&gb.type==='circle')return circleCircleIntersections(ga,gb);return[];}
  function resize(){var rect=wrap.getBoundingClientRect(),dpr=Math.min(2,global.devicePixelRatio||1),w=Math.max(320,Math.round(rect.width)),h=Math.max(440,Math.round(rect.height));if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);canvas.style.width=w+'px';canvas.style.height=h+'px';}ctx.setTransform(dpr,0,0,dpr,0,0);draw();}
  function size(){return{w:canvas.clientWidth||800,h:canvas.clientHeight||650};}
  function toScreen(p){var s=size();return{x:s.w/2+state.origin.x+p.x*state.scale,y:s.h/2+state.origin.y-p.y*state.scale};}
  function toWorld(p){var s=size();return{x:(p.x-s.w/2-state.origin.x)/state.scale,y:-(p.y-s.h/2-state.origin.y)/state.scale};}
  function snap(p){if(!state.snap)return p;var step=state.scale>90?.5:1;return{x:Math.round(p.x/step)*step,y:Math.round(p.y/step)*step};}
  function canvasPoint(event){var r=canvas.getBoundingClientRect();return{x:event.clientX-r.left,y:event.clientY-r.top};}
  function clipLine(line){var s=size(),corners=[toWorld({x:0,y:0}),toWorld({x:s.w,y:0}),toWorld({x:s.w,y:s.h}),toWorld({x:0,y:s.h})],minX=Math.min.apply(null,corners.map(function(p){return p.x;})),maxX=Math.max.apply(null,corners.map(function(p){return p.x;})),minY=Math.min.apply(null,corners.map(function(p){return p.y;})),maxY=Math.max.apply(null,corners.map(function(p){return p.y;})),hits=[];function push(p){if(p.x>=minX-EPS&&p.x<=maxX+EPS&&p.y>=minY-EPS&&p.y<=maxY+EPS&&!hits.some(function(q){return distance(p,q)<1e-5;}))hits.push(p);}var d=line.direction,p=line.point;if(Math.abs(d.x)>EPS){var t=(minX-p.x)/d.x;push(add(p,mul(d,t)));t=(maxX-p.x)/d.x;push(add(p,mul(d,t)));}if(Math.abs(d.y)>EPS){var u=(minY-p.y)/d.y;push(add(p,mul(d,u)));u=(maxY-p.y)/d.y;push(add(p,mul(d,u)));}return hits.slice(0,2);}
  function drawGrid(){var s=size();ctx.fillStyle='#fff';ctx.fillRect(0,0,s.w,s.h);if(state.grid){var step=state.scale,minor=step<35?step*2:step;ctx.strokeStyle=colors.grid;ctx.lineWidth=1;ctx.beginPath();var origin=toScreen({x:0,y:0});for(var x=origin.x%minor;x<s.w;x+=minor){ctx.moveTo(x,0);ctx.lineTo(x,s.h);}for(var y=origin.y%minor;y<s.h;y+=minor){ctx.moveTo(0,y);ctx.lineTo(s.w,y);}ctx.stroke();}if(state.axes){var o=toScreen({x:0,y:0});ctx.strokeStyle=colors.axis;ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(0,o.y);ctx.lineTo(size().w,o.y);ctx.moveTo(o.x,0);ctx.lineTo(o.x,size().h);ctx.stroke();ctx.fillStyle=colors.axis;ctx.font='600 13px "Be Vietnam Pro"';ctx.fillText('x',size().w-18,o.y-8);ctx.fillText('y',o.x+9,16);}}
  function strokeWorld(a,b,style,width,dash){var A=toScreen(a),B=toScreen(b);ctx.save();ctx.strokeStyle=style||colors.line;ctx.lineWidth=width||2;ctx.setLineDash(dash||[]);ctx.beginPath();ctx.moveTo(A.x,A.y);ctx.lineTo(B.x,B.y);ctx.stroke();ctx.restore();}
  function drawObject(o){var g=objectGeometry(o);if(!g)return;ctx.save();ctx.strokeStyle=o.color||colors.line;ctx.lineWidth=2.2;if(g.type==='polygon'){if(g.points.length<2)return;ctx.fillStyle=colors.fill;ctx.beginPath();g.points.forEach(function(p,i){var q=toScreen(p);if(i)ctx.lineTo(q.x,q.y);else ctx.moveTo(q.x,q.y);});ctx.closePath();ctx.fill();ctx.stroke();}else if(g.type==='circle'){var c=toScreen(g.center);ctx.beginPath();ctx.arc(c.x,c.y,g.radius*state.scale,0,Math.PI*2);ctx.stroke();}else if(g.type==='segment'){strokeWorld(g.a,g.b,o.color||colors.line,2.4);}else if(g.line){var clipped=clipLine(g.line);if(clipped.length===2){strokeWorld(clipped[0],clipped[1],o.color||colors.line,2.1,o.type==='parallel'?[9,5]:[]);var label=toScreen(add(g.line.point,mul(g.line.direction,.45/Math.max(EPS,length(g.line.direction)))));ctx.fillStyle=o.color||colors.line;ctx.font='600 13px "Be Vietnam Pro"';ctx.fillText(o.name||'d',label.x+5,label.y-6);}}else if(g.type==='angle'&&g.points.every(Boolean)){var A=g.points[0],B=g.points[1],C=g.points[2],u=sub(A,B),v=sub(C,B),r=28,a1=Math.atan2(-u.y,u.x),a2=Math.atan2(-v.y,v.x),bs=toScreen(B);while(a2<a1)a2+=Math.PI*2;if(a2-a1>Math.PI){var t=a1;a1=a2;a2=t+Math.PI*2;}ctx.strokeStyle=colors.accent;ctx.beginPath();ctx.arc(bs.x,bs.y,r,a1,a2);ctx.stroke();ctx.fillStyle=colors.accent;ctx.font='600 12px "Be Vietnam Pro"';ctx.fillText(Math.round(angleDegrees(A,B,C))+'°',bs.x+34,bs.y-12);}ctx.restore();}
  function drawPoints(){state.points.forEach(function(p){var value=getPoint(p);if(!value)return;var s=toScreen(value);ctx.fillStyle=p.kind==='free'?colors.point:colors.derived;ctx.beginPath();ctx.arc(s.x,s.y,6,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.stroke();if(state.labels){ctx.fillStyle='#1e2935';ctx.font='700 14px "Be Vietnam Pro"';ctx.fillText(p.label,s.x+9,s.y-9);}});}
  function draw(){drawGrid();state.objects.filter(function(o){return o.type==='polygon';}).forEach(drawObject);state.objects.filter(function(o){return o.type!=='polygon';}).forEach(drawObject);drawPoints();}
  function renderList(){var list=$('planeObjectList'),items=[];state.points.forEach(function(p){items.push('<button type="button" data-plane-select="'+p.id+'"><i class="point"></i><span><b>Điểm '+p.label+'</b><small>'+(p.kind==='free'?'Có thể kéo':'Điểm phụ thuộc')+'</small></span></button>');});state.objects.forEach(function(o){var names={segment:'Đoạn thẳng',line:'Đường thẳng',circle:'Đường tròn',polygon:'Đa giác',parallel:'Song song',perpendicular:'Vuông góc',angle:'Góc'};items.push('<button type="button" data-plane-select="'+o.id+'"><i></i><span><b>'+(names[o.type]||o.type)+'</b><small>'+(o.name||'Đối tượng dựng')+'</small></span></button>');});list.innerHTML=items.join('')||'<p>Chưa có hình. Chọn mẫu hoặc bắt đầu bằng một điểm.</p>';$('planeObjectCount').textContent=state.points.length+state.objects.length;list.querySelectorAll('button').forEach(function(btn){btn.onclick=function(){state.selected=btn.dataset.planeSelect;draw();};});}
  function renderAll(){renderList();draw();updateUndo();}
  function setTool(name){state.tool=name;state.steps=[];state.polygon=[];document.querySelectorAll('[data-plane-tool]').forEach(function(btn){btn.classList.toggle('active',btn.dataset.planeTool===name);});var info=toolInfo[name];$('planeHelpIcon').textContent=info[0];$('planeHelpTitle').textContent=info[1];$('planeHelpText').textContent=info[2];$('planeStatus').textContent=info[2];$('finishPolygon').hidden=name!=='polygon';draw();}
  function hitPoint(screen,limit){var best=null,bestD=limit||14;state.points.forEach(function(p){var pos=getPoint(p);if(!pos)return;var d=distance(screen,toScreen(pos));if(d<bestD){best=p;bestD=d;}});return best;}
  function distanceToLineScreen(screen,line){var a=toScreen(line.point),b=toScreen(add(line.point,line.direction)),ab=sub(b,a);return Math.abs(cross(sub(screen,a),ab))/Math.max(EPS,length(ab));}
  function hitObject(screen){var best=null,bestD=13;state.objects.forEach(function(o){var g=objectGeometry(o),d=Infinity;if(!g)return;if(g.line)d=distanceToLineScreen(screen,g.line);else if(g.type==='segment'){var a=toScreen(g.a),b=toScreen(g.b),ab=sub(b,a),t=Math.max(0,Math.min(1,dot(sub(screen,a),ab)/dot(ab,ab)));d=distance(screen,add(a,mul(ab,t)));}else if(g.type==='circle'){d=Math.abs(distance(screen,toScreen(g.center))-g.radius*state.scale);}if(d<bestD){best=o;bestD=d;}});return best;}
  function ensurePoint(screen){var hit=hitPoint(screen);if(hit)return hit;var p=addPoint(snap(toWorld(screen)));return p;}
  function removeEntity(entity){snapshot();var ids={};function markPoint(pid){if(ids[pid])return;ids[pid]=1;state.points.filter(function(p){return p.deps&&p.deps.indexOf(pid)>=0;}).forEach(function(p){markPoint(p.id);});}if(entity.id.charAt(0)==='p')markPoint(entity.id);else ids[entity.id]=1;state.objects=state.objects.filter(function(o){if(ids[o.id])return false;if((o.points||[]).some(function(pid){return ids[pid];})||ids[o.point]||ids[o.base]){ids[o.id]=1;return false;}return true;});state.points=state.points.filter(function(p){return !ids[p.id]&&!(p.deps||[]).some(function(dep){return ids[dep];});});renderAll();}
  function selectStep(screen){var tool=state.tool,p,o;if(['segment','line','circle','polygon','midpoint','angle'].indexOf(tool)>=0){p=ensurePoint(screen);state.steps.push(p.id);if(tool==='polygon'){state.polygon.push(p.id);$('planeStatus').textContent='Đã chọn '+state.polygon.length+' đỉnh · tiếp tục hoặc khép đa giác';renderAll();return;}var needed=tool==='angle'?3:2;if(state.steps.length>=needed){snapshot();if(tool==='midpoint')addPoint({x:0,y:0},{kind:'midpoint',deps:state.steps.slice(0,2)});else addObject(tool,{points:state.steps.slice(0,needed)});state.steps=[];renderAll();}else{draw();}}else if(tool==='intersection'){o=hitObject(screen);if(!o)return;state.steps.push(o.id);if(state.steps.length===2){var hits=intersections(getObject(state.steps[0]),getObject(state.steps[1]));if(hits.length){snapshot();hits.forEach(function(hit,i){addPoint(hit,{kind:'intersection',deps:state.steps.slice(),choice:i});});renderAll();}state.steps=[];}}else if(tool==='parallel'||tool==='perpendicular'){if(!state.steps.length){o=hitObject(screen);if(o&&objectLine(o)){state.steps=[o.id];$('planeStatus').textContent='Bây giờ chọn điểm mà đường mới đi qua';}}else{p=ensurePoint(screen);snapshot();addObject(tool,{base:state.steps[0],point:p.id});state.steps=[];renderAll();}}}
  function pointerDown(event){var screen=canvasPoint(event),p=hitPoint(screen),o=hitObject(screen);canvas.setPointerCapture&&canvas.setPointerCapture(event.pointerId);if(state.tool==='move'){if(p&&p.kind==='free'){snapshot();drag={mode:'point',id:p.id,x:screen.x,y:screen.y};}else drag={mode:'pan',x:screen.x,y:screen.y,start:clone(state.origin)};}else if(state.tool==='point'){snapshot();addPoint(snap(toWorld(screen)));renderAll();}else if(state.tool==='delete'){if(p)removeEntity(p);else if(o)removeEntity(o);}else selectStep(screen);}
  function pointerMove(event){if(!drag.mode)return;var screen=canvasPoint(event);if(drag.mode==='point'){var p=state.points.find(function(x){return x.id===drag.id;});if(p){var world=snap(toWorld(screen));p.x=world.x;p.y=world.y;draw();}}else{state.origin.x=drag.start.x+screen.x-drag.x;state.origin.y=drag.start.y+screen.y-drag.y;draw();}}
  function pointerUp(){if(drag.mode){drag={mode:null};renderList();updateUndo();}}
  function wheel(event){event.preventDefault();var before=toWorld(canvasPoint(event)),factor=event.deltaY<0?1.1:.9;state.scale=Math.max(25,Math.min(180,state.scale*factor));var after=toScreen(before),mouse=canvasPoint(event);state.origin.x+=mouse.x-after.x;state.origin.y+=mouse.y-after.y;draw();}
  function fit(){if(!state.points.length){state.origin={x:0,y:0};state.scale=70;draw();return;}var pts=state.points.map(function(p){return getPoint(p);}).filter(Boolean),minX=Math.min.apply(null,pts.map(function(p){return p.x;})),maxX=Math.max.apply(null,pts.map(function(p){return p.x;})),minY=Math.min.apply(null,pts.map(function(p){return p.y;})),maxY=Math.max.apply(null,pts.map(function(p){return p.y;})),s=size();state.scale=Math.max(35,Math.min(110,Math.min((s.w-140)/Math.max(2,maxX-minX),(s.h-140)/Math.max(2,maxY-minY))));state.origin.x=-(minX+maxX)*.5*state.scale;state.origin.y=(minY+maxY)*.5*state.scale;draw();}
  function clearConstruction(){state.points=[];state.objects=[];state.redo=[];state.steps=[];state.polygon=[];}
  function preset(name){snapshot();clearConstruction();var A,B,C,D,M1,M2,M3,O;if(name==='square'){A=addPoint({x:-3,y:-2},{label:'A'});B=addPoint({x:3,y:-2},{label:'B'});C=addPoint({x:3,y:4},{label:'C'});D=addPoint({x:-3,y:4},{label:'D'});addObject('polygon',{points:[A.id,B.id,C.id,D.id]});addObject('segment',{points:[A.id,C.id]});addObject('segment',{points:[B.id,D.id]});}else{A=addPoint({x:-4,y:-2},{label:'A'});B=addPoint({x:4,y:-2},{label:'B'});C=addPoint({x:1,y:4},{label:'C'});addObject('polygon',{points:[A.id,B.id,C.id]});if(name==='medians'){M1=addPoint({x:0,y:0},{label:'M',kind:'midpoint',deps:[B.id,C.id]});M2=addPoint({x:0,y:0},{label:'N',kind:'midpoint',deps:[A.id,C.id]});M3=addPoint({x:0,y:0},{label:'P',kind:'midpoint',deps:[A.id,B.id]});addObject('segment',{points:[A.id,M1.id]});addObject('segment',{points:[B.id,M2.id]});addObject('segment',{points:[C.id,M3.id]});}if(name==='circumcircle'){var center=circumcenter(getPoint(A.id),getPoint(B.id),getPoint(C.id));O=addPoint(center||{x:0,y:0},{label:'O'});addObject('circle',{points:[O.id,A.id]});}}fit();renderAll();}
  function format(n){return(Math.round(n*1000)/1000).toString();}
  function tikzBody(){var lines=['\\begin{tikzpicture}[scale=0.9,line cap=round,line join=round,>=Stealth]'],names={};state.points.forEach(function(p,index){var q=getPoint(p);names[p.id]='vmP'+index;if(q)lines.push('  \\coordinate ('+names[p.id]+') at ('+format(q.x)+','+format(q.y)+');');});state.objects.forEach(function(o){var g=objectGeometry(o),ids=o.points||[];if(!g)return;if(g.type==='polygon')lines.push('  \\draw[fill=orange!8,thick] '+ids.map(function(pid){return'('+names[pid]+')';}).join(' -- ')+' -- cycle;');else if(g.type==='segment')lines.push('  \\draw[thick] ('+names[ids[0]]+') -- ('+names[ids[1]]+');');else if(g.type==='circle')lines.push('  \\draw[thick] ('+names[ids[0]]+') circle ('+format(g.radius)+');');else if(g.line){var clipped=clipLine(g.line);if(clipped.length===2)lines.push('  \\draw['+(o.type==='parallel'?'dashed,':'')+'thick] ('+format(clipped[0].x)+','+format(clipped[0].y)+') -- ('+format(clipped[1].x)+','+format(clipped[1].y)+') node[pos=.75,above] {$'+(o.name||'d')+'$};');}else if(g.type==='angle'&&g.points.every(Boolean)){lines.push('  \\pic[draw,orange,angle radius=7mm,"$'+Math.round(angleDegrees(g.points[0],g.points[1],g.points[2]))+'^\\circ$"] {angle = '+names[ids[0]]+'--'+names[ids[1]]+'--'+names[ids[2]]+'};');}});state.points.forEach(function(p){if(names[p.id])lines.push('  \\fill ('+names[p.id]+') circle (1.6pt) node[above right] {$'+p.label+'$};');});lines.push('\\end{tikzpicture}');return lines.join('\n');}
  function latexDocument(){return'\\documentclass[border=8pt,tikz]{standalone}\n\\usepackage[T5]{fontenc}\n\\usepackage[utf8]{inputenc}\n\\usepackage{tikz}\n\\usetikzlibrary{calc,intersections,angles,quotes,arrows.meta}\n\\begin{document}\n'+tikzBody()+'\n\\end{document}\n';}
  function download(blob,name){var url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1200);}
  function exportPng(){canvas.toBlob(function(blob){if(blob)download(blob,'hinh-phang-vmtool.png');},'image/png');}
  function svgSource(){var s=size(),out=['<svg xmlns="http://www.w3.org/2000/svg" width="'+s.w+'" height="'+s.h+'" viewBox="0 0 '+s.w+' '+s.h+'"><rect width="100%" height="100%" fill="white"/>'];state.objects.forEach(function(o){var g=objectGeometry(o);if(!g)return;if(g.type==='polygon')out.push('<polygon points="'+g.points.map(function(p){var q=toScreen(p);return q.x+','+q.y;}).join(' ')+'" fill="#f5ae3020" stroke="#174f8a" stroke-width="2"/>');else if(g.type==='segment'){var a=toScreen(g.a),b=toScreen(g.b);out.push('<line x1="'+a.x+'" y1="'+a.y+'" x2="'+b.x+'" y2="'+b.y+'" stroke="#174f8a" stroke-width="2"/>');}else if(g.type==='circle'){var c=toScreen(g.center);out.push('<circle cx="'+c.x+'" cy="'+c.y+'" r="'+g.radius*state.scale+'" fill="none" stroke="#174f8a" stroke-width="2"/>');}else if(g.line){var clip=clipLine(g.line);if(clip.length===2){var x=toScreen(clip[0]),y=toScreen(clip[1]);out.push('<line x1="'+x.x+'" y1="'+x.y+'" x2="'+y.x+'" y2="'+y.y+'" stroke="#174f8a" stroke-width="2"/>');}}});state.points.forEach(function(p){var q=toScreen(getPoint(p));out.push('<circle cx="'+q.x+'" cy="'+q.y+'" r="5" fill="#c34232"/><text x="'+(q.x+9)+'" y="'+(q.y-8)+'" font-family="sans-serif" font-weight="700">'+p.label+'</text>');});return out.join('')+'</svg>';}
  function toast(message){var el=$('vmtoolToast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(function(){el.classList.remove('show');},2500);}
  function openLatex(){var d=$('planeLatexDialog');$('planeLatexSource').value=latexDocument();$('planeLatexStatus').textContent='Sẵn sàng';if(typeof d.showModal==='function')d.showModal();else d.setAttribute('open','');}
  async function compileLatex(){var button=$('planeRunLatex'),preview=$('planeLatexPreview'),status=$('planeLatexStatus'),link=$('planePdfDownload');button.disabled=true;button.textContent='⏳ Đang biên dịch…';status.textContent='Đang gửi bản LaTeX tới trạm biên dịch…';preview.innerHTML='<div class="vmtool-latex-empty is-loading"><span></span><b>Đang dựng PDF</b><p>Thường mất vài giây.</p></div>';try{if(!global.sb||!sb.auth||!sb.functions)throw new Error('Chưa kết nối được dịch vụ VinhMath.');var session=await sb.auth.getSession();if(!session.data||!session.data.session)throw new Error('Phiên đăng nhập đã hết hạn. Hãy đăng nhập lại.');var result=await sb.functions.invoke('latex',{body:{tex:$('planeLatexSource').value,engine:'pdflatex'}});if(result.error)throw new Error(result.error.message||'Trạm biên dịch đang bận.');if(!(result.data instanceof Blob)||result.data.type.indexOf('pdf')<0){var log=typeof result.data==='string'?result.data:await result.data.text();throw new Error(String(log||'Không nhận được PDF').split('\n').filter(function(line){return line.indexOf('!')===0||/error/i.test(line);}).slice(0,3).join(' ')||'Không nhận được PDF.');}if(state.pdfUrl)URL.revokeObjectURL(state.pdfUrl);state.pdfUrl=URL.createObjectURL(result.data);preview.innerHTML='<iframe title="Xem trước hình LaTeX" src="'+state.pdfUrl+'#view=FitH"></iframe>';link.href=state.pdfUrl;link.download='hinh-phang-vmtool.pdf';link.hidden=false;status.textContent='Biên dịch thành công';toast('Đã biên dịch hình LaTeX thành PDF.');}catch(error){preview.innerHTML='<div class="vmtool-latex-empty is-error"><span>!</span><b>Chưa tạo được PDF</b><p>'+String(error.message||error).replace(/[<>]/g,'')+'</p></div>';status.textContent='Có lỗi khi biên dịch';}finally{button.disabled=false;button.textContent='▶ Biên dịch PDF';}}
  function bind(){document.querySelectorAll('[data-plane-tool]').forEach(function(btn){btn.onclick=function(){setTool(btn.dataset.planeTool);};});document.querySelectorAll('[data-plane-preset]').forEach(function(btn){btn.onclick=function(){preset(btn.dataset.planePreset);};});canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',pointerUp);canvas.addEventListener('wheel',wheel,{passive:false});$('finishPolygon').onclick=function(){if(state.polygon.length>=3){snapshot();addObject('polygon',{points:state.polygon.slice()});state.polygon=[];state.steps=[];renderAll();}};$('planeUndo').onclick=undo;$('planeRedo').onclick=redo;$('planeFit').onclick=fit;$('planeFullscreen').onclick=function(){if(document.fullscreenElement)document.exitFullscreen();else card.requestFullscreen&&card.requestFullscreen();};document.addEventListener('fullscreenchange',resize);$('planeGrid').onchange=function(){state.grid=this.checked;draw();};$('planeSnap').onchange=function(){state.snap=this.checked;};$('planeAxes').onchange=function(){state.axes=this.checked;draw();};$('planeLabels').onchange=function(){state.labels=this.checked;draw();};$('planePng').onclick=exportPng;$('planeSvg').onclick=function(){download(new Blob([svgSource()],{type:'image/svg+xml'}),'hinh-phang-vmtool.svg');};$('planeTikz').onclick=function(){download(new Blob([latexDocument()],{type:'text/plain;charset=utf-8'}),'hinh-phang-vmtool.tex');};$('planeCompile').onclick=openLatex;$('planeCopyLatex').onclick=async function(){await navigator.clipboard.writeText($('planeLatexSource').value);toast('Đã sao chép mã LaTeX.');};$('planeDownloadTex').onclick=function(){download(new Blob([$('planeLatexSource').value],{type:'text/plain;charset=utf-8'}),'hinh-phang-vmtool.tex');};$('planeRunLatex').onclick=compileLatex;if(global.ResizeObserver){resizeObserver=new ResizeObserver(resize);resizeObserver.observe(wrap);}global.addEventListener('resize',resize);document.addEventListener('vmtool:tab',function(e){if(e.detail&&e.detail.name==='plane')setTimeout(resize,0);});}
  function init(){bind();preset('triangle');setTool('move');resize();global.VMToolPlaneState=state;global.VMToolPlaneExport={tikz:tikzBody,latex:latexDocument,svg:svgSource};}
  init();
})(typeof window!=='undefined'?window:globalThis);
