const assert=require('node:assert/strict'),fs=require('node:fs'),{spawn}=require('node:child_process');
const {chromium}=require('C:/Users/PC/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const server=spawn('C:/Users/PC/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',['scripts/serve.py','--port','8793'],{windowsHide:true,stdio:'ignore'});
(async()=>{await new Promise(r=>setTimeout(r,700));const b=await chromium.launch({channel:'chrome',headless:true});const out='.tools/test-artifacts/vmtools-intro';fs.mkdirSync(out,{recursive:true});try{
for(const width of [1366,390])for(const theme of ['dark','light']){const p=await b.newPage({viewport:{width,height:900}});await p.addInitScript(t=>{localStorage.setItem('vmtools-promo-theme',t);localStorage.setItem('vmtools-theme-mode',t);},theme);await p.route('**/functions/v1/vmtools-license',r=>r.fulfill({json:{release:{version:'0.5.2',notes:'Release notes'},files:['win32','darwin'].flatMap(platform=>['installer','update_manifest'].map(kind=>({id:platform+kind,platform,arch:platform==='darwin'?'arm64':'x64',kind,version:'0.5.2',file_name:'VMTools-0.5.2',size:kind==='update_manifest'?501:platform==='darwin'?166270302:122986782}))),trial:{allowed:true}}}));
await p.goto('http://127.0.0.1:8793/vmtool');await p.locator('#vm-downloads article').first().waitFor();assert.equal(await p.locator('#vmtools-content > section').first().getAttribute('id'),'download');assert.equal(await p.locator('h1').count(),1);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
if(width>760){const cards=await p.locator('#vm-downloads').boundingBox();assert.ok(cards.y+cards.height<800);}
assert.equal(await p.locator('#release-notes').isVisible(),false);await p.screenshot({path:`${out}/portal-${width}-${theme}.png`});
await p.getByRole('button',{name:'Quét mã Zalo'}).click();await p.locator('dialog img').waitFor();assert.equal(await p.locator('dialog img').getAttribute('src'),'/assets/vmtools/zalo-the-vinh.png');await p.screenshot({path:`${out}/qr-${width}-${theme}.png`});await p.keyboard.press('Escape');await p.locator('dialog').waitFor({state:'detached'});assert.equal(await p.locator('dialog').count(),0);
await p.goto('http://127.0.0.1:8793/');await p.locator('[data-vinh-contact] a').first().waitFor();await p.locator('#vm-preloader').waitFor({state:'hidden'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await p.locator('a[href^="tel:"]').count(),0);assert.equal(await p.locator('[data-vinh-contact] a').first().getAttribute('href'),'https://www.facebook.com/ienvothevinh');await p.screenshot({path:`${out}/home-${width}-${theme}.png`});await p.locator('.vm-home-showcase').screenshot({path:`${out}/intro-${width}-${theme}.png`});await p.close();}
console.log('PASS desktop/mobile dark/light: downloads first, one h1, no overflow, shared contact links, QR dialog and Escape, release notes collapsed');
}finally{await b.close();server.kill();}})().catch(e=>{console.error(e);server.kill();process.exitCode=1});
