const fs=require('fs'),http=require('http'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.VM_PLAYWRIGHT||'playwright');
(async()=>{
 const root=process.cwd(),server=http.createServer((req,res)=>{const p=new URL(req.url,'http://localhost').pathname;const file=path.resolve(root,'.'+p);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404).end();return;}let body=fs.readFileSync(file);if(file.endsWith('.html'))body=body.toString().replace(/<script\b[^>]*src="(?!js\/teacher-services\.js)[^"]*"[^>]*><\/script>/g,'');res.setHeader('Content-Type',file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.js')?'text/javascript':'text/css');res.end(body);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.VM_CHROME_PATH,headless:true});
 try{
  const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.calls=[];window.sb={functions:{invoke:async(name,{body})=>{calls.push(body);return {data:body.action==='list'?{teachers:[{id:'t1',role:'teacher',full_name:'Nguyễn Minh Anh',email:'teacher@example.com'},{id:'s1',role:'student',full_name:'Học sinh thử nghiệm',username:'student-test'}],classroom:[{user_id:'t1',status:'active',plan:'lifetime'}],vmtools:[{id:'v1',auth_user_id:'t1',status:'pending',plan:'monthly',email:'teacher@example.com'}],payments:[],vmPayments:[],classroomEnforced:false}:{ok:true}};}}};});
  await page.goto('http://127.0.0.1:'+server.address().port+'/quan-tri-dich-vu.html');await page.getByRole('heading',{name:'Quản lý dịch vụ'}).waitFor();await page.locator('[data-service=vmtools] [data-action=renew]').click();await page.locator('[name=confirm]').check();await page.getByRole('button',{name:'Xác nhận',exact:true}).click();assert.equal((await page.evaluate(()=>calls.find(c=>c.action==='renew'))).service,'vmtools');
  await page.locator('#services-role').selectOption('student');assert.equal(await page.locator('tr[data-user]:visible').count(),1);await page.locator('[data-action=link-student]').click();assert.ok(await page.locator('dialog').isVisible());await page.locator('dialog [data-cancel]').click();await page.locator('#services-role').selectOption('');
  const capture=process.env.VM_QA_DIR;if(capture)await page.screenshot({path:path.join(capture,'web-services-desktop.png')});await page.setViewportSize({width:820,height:1180});if(capture)await page.screenshot({path:path.join(capture,'web-services-tablet.png')});
  await page.getByPlaceholder('Tìm tên, tài khoản, email').fill('không có');assert.equal(await page.locator('tr[data-user]:visible').count(),0);assert.deepEqual(errors,[]);
  console.log('PASS desktop/tablet services UI; correct renewal service; search; no page errors');
 }finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
