const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
const base=(process.env.VM_BASE_URL||'http://127.0.0.1:8765').replace(/\/$/,''),dir=process.env.VM_GAME_QA_DIR;
const delay=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{const browser=await chromium.launch({executablePath:process.env.VM_CHROME_PATH,headless:true});const evidence=[];try{
 for(const width of (process.env.VM_MOTION_WIDTHS||'390,1440,2560').split(',').map(Number)){
  const context=await browser.newContext({viewport:{width,height:width===390?844:width===2560?1440:1000},reducedMotion:'no-preference'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'/vmgame.html');assert(await page.locator('#arrival').isVisible());const entrance1=await page.locator('#scene').evaluate(e=>getComputedStyle(e).transform);await delay(300);const entrance2=await page.locator('#scene').evaluate(e=>getComputedStyle(e).transform);assert.notEqual(entrance1,entrance2);await page.locator('#skip-arrival').click();assert(await page.locator('#arrival').isHidden());
  await page.waitForFunction(()=>document.querySelector('#scene').dataset.layers==='registered');
  const sample=()=>page.evaluate(()=>{const water=document.querySelector('#scene .vm-environment-canvas:not(.vm-light-canvas)'),ctx=water.getContext('2d');const d=ctx.getImageData(0,0,water.width,water.height).data;let hash=0,lit=0;for(let i=3;i<d.length;i+=4){hash=(hash*31+d[i])>>>0;if(d[i]>20)lit++}return{waterHash:hash,waterLit:lit,frame:+water.dataset.frame,cloud:getComputedStyle(document.querySelector('#scene .vm-cloud-0')).transform,portrait:getComputedStyle(document.querySelector('#hero-character')).transform}});
  const before=await sample(),image1=await page.screenshot();await delay(1400);const after=await sample(),image2=await page.screenshot();assert(after.frame-before.frame>=12,'Visible scene draws over time');assert.notEqual(before.waterHash,after.waterHash,'Water pixels move');assert(before.waterLit>100,'Visible water glints');assert.notEqual(before.cloud,after.cloud,'Clouds drift');assert.notEqual(before.portrait,after.portrait,'Portrait idles');
  const changedPixels=await page.evaluate(async([a,b])=>{const imgs=await Promise.all([a,b].map(s=>new Promise(resolve=>{const i=new Image();i.onload=()=>resolve(i);i.src='data:image/png;base64,'+s})));const c=document.createElement('canvas');c.width=imgs[0].width;c.height=imgs[0].height;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(imgs[0],0,0);const first=x.getImageData(0,0,c.width,c.height).data;x.clearRect(0,0,c.width,c.height);x.drawImage(imgs[1],0,0);const second=x.getImageData(0,0,c.width,c.height).data;let changed=0;for(let i=0;i<first.length;i+=4)if(Math.abs(first[i]-second[i])+Math.abs(first[i+1]-second[i+1])+Math.abs(first[i+2]-second[i+2])>25)changed++;return changed},[image1.toString('base64'),image2.toString('base64')]);assert(changedPixels>width*3,'Rendered pixels visibly change, not just animation names');
  await page.locator('#day-night').click();assert(await page.locator('body').evaluate(e=>e.classList.contains('night-world')));const lights=await page.locator('#scene .vm-light-canvas').evaluate(c=>{const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let warm=0;for(let i=0;i<d.length;i+=4)if(d[i]>d[i+2]+30&&d[i+3]>60)warm++;return warm});assert(lights>50,'Night has emissive warm lighting');
  const nightBefore=await sample();await delay(450);const nightAfter=await sample();assert.notEqual(nightBefore.waterHash,nightAfter.waterHash,'Night reflections and water move');assert.notEqual(nightBefore.cloud,nightAfter.cloud,'Clouds also drift at night');
  await page.locator('#scholar-interact').click();assert(await page.evaluate(()=>!document.querySelector('#scholar-speech').hidden&&document.querySelector('.active-scholar').classList.contains('scholar-greeting')));
  if(dir){fs.mkdirSync(dir,{recursive:true});await page.screenshot({path:path.join(dir,'night-'+width+'.png')})}
  await page.locator('#motion').click();assert.equal(await page.locator('#motion').getAttribute('aria-pressed'),'false');await delay(80);const stopped=await sample();await delay(350);assert.deepEqual(await sample(),stopped,'Motion off freezes cloud, water and scholar');await page.reload();assert(await page.locator('#motion-explanation').innerText());assert(await page.locator('#motion').isVisible());assert(await page.locator('#arrival').isHidden());await page.locator('#motion').click();await page.locator('#replay-arrival').click();assert(await page.locator('#arrival').isVisible());await page.keyboard.press('Escape');assert(await page.locator('#arrival').isHidden());
  await page.emulateMedia({reducedMotion:'reduce'});await delay(60);const reduced=await sample();await delay(300);assert.deepEqual(await sample(),reduced,'OS reduced motion freezes all environmental layers');assert(await page.locator('#replay-arrival').isDisabled());await page.locator('#motion').click();assert.equal(await page.locator('#motion').getAttribute('aria-pressed'),'false');assert((await page.locator('#motion-explanation').innerText()).includes('thiết bị'));
  await page.emulateMedia({reducedMotion:'no-preference'});await page.goto(base+'/');const promo=await page.locator('#vmgame').boundingBox();assert(promo.y<150,'Promotion is visible at the top');assert(await page.locator('.vmgame-proof-cta').isVisible());assert((await page.locator('.vmgame-proof-cta').boundingBox()).y<840,'Math CTA fits initial phone viewport');const previewFrame=await page.locator('#vmgame-preview .vm-environment-canvas:not(.vm-light-canvas)').getAttribute('data-frame');await delay(400);assert.notEqual(await page.locator('#vmgame-preview .vm-environment-canvas:not(.vm-light-canvas)').getAttribute('data-frame'),previewFrame);await page.locator('#preview-night').click();await page.locator('#preview-motion').click();await delay(80);const frozen=await page.locator('#vmgame-preview .vm-environment-canvas:not(.vm-light-canvas)').getAttribute('data-frame');await delay(250);assert.equal(await page.locator('#vmgame-preview .vm-environment-canvas:not(.vm-light-canvas)').getAttribute('data-frame'),frozen);
  if(dir)await page.screenshot({path:path.join(dir,'homepage-'+width+'.png')});assert.deepEqual(errors,[]);evidence.push({width,changedPixels,waterPixels:before.waterLit,renderedFrames:after.frame-before.frame,warmNightPixels:lights});await context.close();
 }
 console.log('PASS observable VMGame motion, skippable entrance, night illumination, greeting, pause/persistence/OS reduced motion, and top homepage promotion:',JSON.stringify(evidence));if(dir)fs.writeFileSync(path.join(dir,'motion-evidence.json'),JSON.stringify(evidence,null,2));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
