const {chromium}=require('C:/Users/PC/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const {spawn}=require('child_process'),assert=require('assert/strict'),fs=require('fs');
const target=process.env.VMTOOLS_TEST_URL||'http://127.0.0.1:8796/';
fs.mkdirSync('.tools/test-artifacts/vmtools-launch',{recursive:true});
const server=process.env.VMTOOLS_TEST_URL?null:spawn('C:/Users/PC/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',['scripts/serve.py','--port','8796'],{windowsHide:true,stdio:'ignore'});
(async()=>{await new Promise(r=>setTimeout(r,700));const b=await chromium.launch({channel:'chrome',headless:true});try{for(const mobile of [false,true]){const p=await b.newPage({viewport:{width:mobile?390:1366,height:900},hasTouch:true,isMobile:mobile});await p.addInitScript(()=>{window.orbitFrames=0;const clear=CanvasRenderingContext2D.prototype.clearRect;CanvasRenderingContext2D.prototype.clearRect=function(...args){if(this.canvas.classList.contains('vm-orbit-canvas'))window.orbitFrames++;return clear.apply(this,args);};});await p.goto(target);await p.locator('#vm-preloader').waitFor({state:'hidden'});const host=p.locator('.vm-launch'),scene=host.locator('.vm-orbit-scene'),canvas=host.locator('.vm-orbit-canvas');await canvas.scrollIntoViewIfNeeded();await p.waitForTimeout(100);const first=await p.evaluate(()=>orbitFrames);await p.waitForTimeout(600);assert.ok((await p.evaluate(()=>orbitFrames))-first>8,'continuous frames');const r=await canvas.boundingBox(),x=r.x+r.width*.68,y=r.y+25;
 const start=Number(await scene.getAttribute('data-yaw'));await p.mouse.move(x,y);await p.mouse.down();await p.mouse.move(x+50,y+20,{steps:8});await p.mouse.up();assert.ok(Math.abs(Number(await scene.getAttribute('data-yaw'))-start)>.2);
 const z=Number(await scene.getAttribute('data-zoom'));await p.mouse.wheel(0,-130);await p.waitForTimeout(80);assert.ok(Number(await scene.getAttribute('data-zoom'))>z);await host.locator('[data-orbit-reset]').click();assert.equal(await scene.getAttribute('data-zoom'),'1.000');
 const cdp=await p.context().newCDPSession(p),touch=(id,dx)=>({id,x:x+dx,y,radiusX:4,radiusY:4,force:1});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch(1,-25),touch(2,25)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[touch(1,-55),touch(2,55)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(Number(await scene.getAttribute('data-zoom'))>1.3,'two-finger zoom');
 const oldYaw=Number(await scene.getAttribute('data-yaw'));await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch(3,-10)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[touch(3,40)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(Number(await scene.getAttribute('data-yaw'))>oldYaw+.2,'one-finger rotation');
 await host.locator('[data-orbit-reset]').click();await host.locator('.vm-motion').click();await p.waitForTimeout(80);const frozen=await p.evaluate(()=>orbitFrames);await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>orbitFrames),frozen,'pause stops rendering');await host.locator('.vm-motion').click();await canvas.scrollIntoViewIfNeeded();await p.waitForTimeout(150);assert.ok(await p.evaluate(()=>orbitFrames)>frozen);
 await p.evaluate(()=>scrollTo(0,document.body.scrollHeight));await p.waitForTimeout(150);const hidden=await p.evaluate(()=>orbitFrames);await p.waitForTimeout(150);assert.equal(await p.evaluate(()=>orbitFrames),hidden,'offscreen stops rendering');
 await canvas.scrollIntoViewIfNeeded();await p.emulateMedia({reducedMotion:'reduce'});await p.waitForTimeout(100);assert.equal(await host.locator('.vm-motion').getAttribute('aria-pressed'),'false');const reduced=await p.evaluate(()=>orbitFrames);await p.waitForTimeout(150);assert.equal(await p.evaluate(()=>orbitFrames),reduced);await canvas.focus();await p.keyboard.press('+');assert.ok(Number(await scene.getAttribute('data-zoom'))>1,'keyboard remains interactive when paused');
 await host.locator('[data-orbit-reset]').click();await host.screenshot({path:`.tools/test-artifacts/vmtools-launch/interactive-${mobile?'mobile':'desktop'}.png`});await p.close();}
console.log('PASS mouse drag, wheel, touch drag, two-finger pinch, keyboard, reset, continuous animation, pause, reduced motion and offscreen suspension on desktop/mobile');}finally{await b.close();server?.kill()}})().catch(e=>{console.error(e);server?.kill();process.exitCode=1});
