const assert=require('assert/strict'),fs=require('fs'),{spawn}=require('child_process');
const {chromium}=require('C:/Users/PC/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const server=spawn('C:/Users/PC/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',['scripts/serve.py','--port','8791'],{windowsHide:true,stdio:'ignore'});
(async()=>{await new Promise(r=>setTimeout(r,700));const b=await chromium.launch({channel:'chrome',headless:true});fs.mkdirSync('.tools/test-artifacts/vmtools-comfort',{recursive:true});try{
for(const theme of ['dark','light']){const p=await b.newPage();await p.addInitScript(t=>{localStorage.setItem('vmtools-theme-mode',t);localStorage.setItem('vmtools-promo-theme',t)},theme);await p.route('**/*.css*',r=>r.abort());await p.route('**/assets/*.js',r=>r.abort());await p.route('**/js/vmtools-portal.js*',r=>r.abort());await p.route('**/js/vmtools-showcase.js*',r=>r.abort());for(const url of ['/vmtool','/vmtools/web-entry.html']){await p.goto('http://127.0.0.1:8791'+url);const colors=await p.evaluate(()=>[getComputedStyle(document.documentElement).backgroundColor,getComputedStyle(document.body).backgroundColor]);assert(colors.every(c=>theme==='dark'?c!=='rgb(255, 255, 255)'&&c!=='rgba(0, 0, 0, 0)':c==='rgb(255, 255, 255)'),theme+' startup '+url+': '+colors);}await p.close();}
for(const width of [1366,390]){const p=await b.newPage({viewport:{width,height:768}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/functions/v1/vmtools-license',r=>r.fulfill({json:{files:[],trial:{allowed:true}}}));await p.route('**/vmtools/web-entry.html*',r=>r.fulfill({contentType:'text/html',body:'<body style="background:#0d1117;color:white"><input aria-label="Lesson" value="Saved work"></body>'}));await p.goto('http://127.0.0.1:8791/vmtool?tab=web');await p.waitForSelector('.vm-working iframe');const frame=p.frameLocator('.vm-web-workspace');await frame.getByRole('textbox',{name:'Lesson'}).fill('Keep this lesson');await p.evaluate(()=>window.testFrame=document.querySelector('iframe'));const header=await p.locator('.vmtools-portal-head').boundingBox();assert.equal(header.height,width>760?40:44);await p.getByRole('button',{name:'Ẩn thanh điều hướng',exact:true}).click();assert.equal((await p.locator('.vm-web-workspace').boundingBox()).height,768);await p.getByRole('button',{name:'Hiện thanh điều hướng',exact:true}).click();assert.equal(await frame.getByRole('textbox',{name:'Lesson'}).inputValue(),'Keep this lesson');assert(await p.evaluate(()=>testFrame===document.querySelector('iframe')));await p.locator('#show-downloads').click();assert.equal(await p.locator('#vm-show-toolbar').isVisible(),false);await p.goto('http://127.0.0.1:8791/');await p.getByRole('link',{name:'Trải nghiệm ngay VMTools trên web'}).waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.locator('#vm-preloader').waitFor({state:'hidden'});await p.locator('.vm-home-showcase').screenshot({path:'.tools/test-artifacts/vmtools-comfort/promo-'+width+'.png'});assert.deepEqual(errors,[]);await p.close();}
for(const allowed of [false,true]){const p=await b.newPage();await p.route('**/functions/v1/vmtools-license',r=>r.fulfill({json:{files:[],access:{},trial:{allowed}}}));await p.route('**/vmtools/web-entry.html*',r=>r.fulfill({contentType:'text/html',body:'Trial workspace'}));await p.goto('http://127.0.0.1:8791/vmtool');await p.waitForSelector('[data-open-web]');await p.locator('#use-web').click();if(allowed)await p.waitForSelector('iframe.vm-web-workspace');else await p.waitForURL('**/dang-nhap?redirect=vmtool');await p.close();}
console.log('PASS guest trial access gates; dark/light initial paint with CSS/modules unavailable; compact toolbar, hide/show retains iframe and lesson; desktop/mobile CTA and author layout');
}finally{await b.close();server.kill()}})().catch(e=>{console.error(e);server.kill();process.exitCode=1});
