const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('js/menu-v5.js','utf8'),nav={innerHTML:'',querySelectorAll:()=>[],querySelector:()=>null},noop=()=>{};
const ctx={document:{querySelector:s=>s==='.navlinks'?nav:null,querySelectorAll:()=>[],getElementById:()=>({}),readyState:'loading',addEventListener:noop,body:{classList:{add:noop}},documentElement:{classList:{add:noop}}},window:{},location:{pathname:'/vmgame'},sessionStorage:{getItem:()=>null,removeItem:noop,setItem:noop},console};
vm.createContext(ctx);vm.runInContext(source,ctx);ctx.damBaoNutMenuMobile=noop;ctx.vmMenuSaveShell=noop;ctx.vmTenantFeatureState=()=> 'hidden';ctx.vmTenantFeatureConfig=()=>({state:'hidden'});
for(const role of ['admin','teacher','assistant','parent','student']){ctx.apDungMenu(role,null,null,{items:[]});assert.equal((nav.innerHTML.match(/href="vmgame"/g)||[]).length,1,role);ctx.apDungMenu(role,null,{full_site:true,features:[]},{items:[]});assert.equal((nav.innerHTML.match(/href="vmgame"/g)||[]).length,0,'tenant '+role);}
ctx.apDungMenu('student',{portal_only:true,portal:{slug:'test'},member_role:'student'},null,null);assert(!nav.innerHTML.includes('href="vmgame"'));
const world=fs.readFileSync('assets/vmgame/world.js','utf8');const start=world.indexOf('const characters='),end=world.indexOf('const buildings=');assert(start>=0&&end>start);const data=vm.runInNewContext(world.slice(start,end)+';({characters,regions})');const names=['Lạc Vân','Phong Diệp','Vân Giang','Thanh Sơn','Tinh Tú','Ngân Kiều','Chân Trời','Bắc Quang'];for(const item of [...data.characters,...data.regions])assert((names.includes(item.country)||item.country==='Hội đồng'),item.country);assert.equal(data.characters.length,10);assert.equal(data.regions.length,8);
assert(!/chiến tranh|quân đội|chinh phạt|conquest|army/i.test(world));
console.log('PASS VMGame entries: all five native roles, tenant/portal isolation, ten scholars and eight fictional region labels, peaceful council content.');
