const fs = require('fs');
const path = require('path');
const vm = require('vm');
const root = path.resolve(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8').replace(/\r\n/g, '\n');
const expect = (value, message) => { if (!value) throw new Error(message); };
const compile = (file) => new vm.Script(read(file), { filename: file });
const compileInline = (file) => {
  const html = read(file);
  [...html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)]
    .map((match) => match[1]).filter((source) => source.trim())
    .forEach((source, index) => new vm.Script(source, { filename: `${file}#${index + 1}` }));
  return html;
};

for (const file of ['js/menu-v5.js', 'js/vinhmath.js', 'js/exam-portal.js', 'js/portal-classroom.js', 'js/exam-admin.js', 'js/role-home.js', 'js/student-results.js']) compile(file);
const login = compileInline('dang-nhap.html');
const classAdmin = compileInline('quan-tri-lop.html');
const exam = compileInline('luyen-de.html');
const hub = compileInline('quan-tri.html');
const portalAdmin = compileInline('quan-tri-portal-thi.html');
const portal = read('thi.html');
const migration = read('supabase/migrations/20260822122518_partner_exam_portals.sql');
const optimization = read('supabase/migrations/20260822125005_optimize_partner_exam_portal_policies.sql');
const hardening = read('supabase/migrations/20260822125416_harden_partner_portal_scope.sql');
const loginSuffix = read('supabase/migrations/20260822125510_partner_portal_login_suffix.sql');
const teacherSuffix = read('supabase/migrations/20260822131500_partner_portal_teacher_suffix.sql');
const toanThayTruong = read('supabase/migrations/20260822152556_add_toan_thay_truong_demo_portal.sql');
const classroom = read('supabase/migrations/20260822172114_partner_portal_classroom_workspace.sql');
const classroomHardening = read('supabase/migrations/20260822173332_harden_partner_portal_classroom_write_scope.sql');
const classroomReturningFix = read('supabase/migrations/20260822173559_fix_partner_portal_hardened_insert_returning.sql');
const unifiedMigration = read('supabase/migrations/20260828143000_unify_admin_brand_theme_feature_access.sql');
const accountFunction = read('supabase/functions/tao-tai-khoan/index.ts');
const menu = read('js/menu-v5.js');
const shared = read('js/vinhmath.js');
const roleHome = read('js/role-home.js');
const examAdmin = read('js/exam-admin.js');

expect(menu.includes("path: 'trang-chu', label: 'Hôm nay'") && menu.includes("path: 'quan-tri', label: 'Quản trị'"), 'Role navigation is not task-focused');
expect(hub.includes('Thương hiệu & không gian') && (hub.match(/href="quan-tri-khong-gian"/g) || []).length === 1, 'Admin tools must expose one unified brand/tenant/portal hub');
expect(!hub.includes('href="quan-tri-portal-thi"') && !hub.includes('href="quan-tri-thuong-hieu"'), 'Legacy portal and brand pages must not remain competing hub shortcuts');
expect(portalAdmin.includes("get('embed')==='1'") && portalAdmin.includes("location.replace('quan-tri-khong-gian?panel=exam&legacy=1')"), 'Legacy portal URL must redirect into the unified manager while supporting its embedded workflow');
expect(menu.includes('function vmMenuFeatureMap(access)') && menu.includes("sb.rpc('vm_my_feature_access'"), 'Role UX must consume server-authoritative effective feature access');
expect(menu.includes('apDungMenu(r.data.role, portalContext, tenantContext, featureAccess)'), 'Shared menu must receive all four role/portal/tenant/access inputs');
expect(menu.includes('function vmMenuTenantExamFocus(context)') && menu.includes("role === 'student' && vmMenuTenantExamFocus(fullSiteTenant)"), 'Student exam focus must be a presentation state of the shared tenant menu');
expect(roleHome.includes('Việc cần ưu tiên') && roleHome.includes('Việc cần làm & cập nhật'), 'Teacher/student home priorities are incomplete');
expect(classAdmin.includes("localStorage.getItem('vm-admin-active-class-id')") && classAdmin.includes("dsLop[0] && dsLop[0].id"), 'Class manager must select a valid class immediately');
expect(classAdmin.includes("currentUrl.searchParams.set('tab', tab)"), 'Class tab state must survive reloads');
expect(shared.includes('/@hs$/') && shared.includes('/@(hs|gv)[a-z0-9]{2,20}$/') && shared.includes('/@hs\\.[a-z0-9]+(?:-[a-z0-9]+)*$/') && login.includes('vmDichDangNhap'), 'Default, compact student/teacher and legacy login routing is missing');
expect(portal.includes('Không gian lớp học riêng') && portal.includes('Bài học') && portal.includes('Nội dung') && !portal.includes('js/menu-v5.js'), 'Portal must have a minimal independent classroom shell');
expect(!/Góc học tập|Bảng vàng|Cá nhân/.test(portal), 'Partner portal must not inherit unnecessary VinhMath navigation');
expect(portal.includes('js/portal-classroom.js') && portal.includes('portalPanelLearn'), 'Portal classroom workspace is not loaded');
expect(portal.includes('portalAuthorLink') && portal.includes('portalAuthorCta'), 'Portal managers need a visible dedicated exam-authoring entry point');
expect(menu.includes("label: 'Soạn đề'") && menu.includes("allowed.push('quan-tri-de')"), 'Only portal managers should be routed into the dedicated exam workspace');
for (const fragment of ["loadPortalManager(profile)", "eq('portal_id',state.portal.id)", "portal_id: state.portal ? state.portal.id : null", "sb.from('exam_portal_exams').upsert"]) expect(examAdmin.includes(fragment), `Portal exam authoring is missing ${fragment}`);
expect(exam.includes('vmPortalExamIds') && exam.includes('vmPortalExamIds.indexOf(exam.id) !== -1'), 'Exam engine is not constrained to portal assignments');
expect(portalAdmin.includes('portal_hs') && portalAdmin.includes('portal_gv') && portalAdmin.includes('exam_portal_exams') && portalAdmin.includes('Xem portal'), 'Portal account, exam and admin preview workflow is incomplete');
expect(portalAdmin.includes('portal_only:false') && !portalAdmin.includes("portal_only:role==='student'"), 'Existing VinhMath accounts must not become portal-only through manual membership');
expect(accountFunction.includes('prof.role !== "admin"') && accountFunction.includes('portal_only: true') && accountFunction.includes('isManager ? "manager" : "student"'), 'Portal account creation must be admin-only and portal-only');
expect(accountFunction.includes('portal.login_suffix') && accountFunction.includes('portal.teacher_login_suffix') && accountFunction.includes('type === "portal_gv"') && !accountFunction.includes('@hs.${portal.slug}'), 'Portal student and teacher accounts must use configured compact suffixes');
expect(!accountFunction.includes('role: "teacher"') || accountFunction.includes('type === "gv"'), 'Partner account must never receive broad teacher access');
for (const helper of ['private.is_portal_only_user()', 'private.can_manage_exam_portal', 'private.can_access_portal_exam', 'private.can_access_portal_question']) expect(migration.includes(helper), `Missing RLS helper ${helper}`);
for (const policy of ['exams_portal_only_scope', 'exam_questions_portal_assigned_read', 'questions_portal_assigned_read', 'profiles_portal_only_scope', 'classes_portal_only_scope', 'lessons_portal_only_scope']) expect(migration.includes(policy), `Missing isolation policy ${policy}`);
expect(migration.includes('as restrictive') && migration.includes('portal_only'), 'Portal isolation must use restrictive RLS');
expect(optimization.includes('exam_portals_brand_idx') && optimization.includes('exam_portals_created_by_idx'), 'Portal foreign keys need covering indexes');
expect(optimization.includes('exam_portals_admin_insert') && !optimization.includes('for all'), 'Admin writes must not create duplicate permissive SELECT policies');
for (const table of ['class_students', 'documents', 'topics', 'schedules', 'submissions', 'class_posts', 'student_lesson_progress', 'lesson_item_progress', 'class_sessions', 'attendance']) expect(hardening.includes(`${table}_portal_only_scope`), `Portal-only account can still reach ${table}`);
expect(loginSuffix.includes("login_suffix ~ '^hs[a-z0-9]{2,20}$'") && loginSuffix.includes('unique (login_suffix)') && loginSuffix.includes("login_suffix <> 'hs'"), 'Portal suffix must be compact, reserved-safe and unique');
expect(teacherSuffix.includes("teacher_login_suffix ~ '^gv[a-z0-9]{2,20}$'") && teacherSuffix.includes('unique (teacher_login_suffix)') && teacherSuffix.includes("teacher_login_suffix <> 'gv'"), 'Portal teacher suffix must be compact, reserved-safe and unique');
expect(toanThayTruong.includes("'toan-thay-truong'") && toanThayTruong.includes("'hstt'") && toanThayTruong.includes("'gvtt'"), 'Toán Thầy Trường brand and suffix pair are missing');
expect(toanThayTruong.includes('exam_portal_members_one_private_portal_per_user_idx') && toanThayTruong.includes('where portal_only'), 'Private portal routing must be unambiguous per account');
expect(toanThayTruong.includes("'site:logo/toan-thay-truong-logo.svg'"), 'Toán Thầy Trường must use its checked-in logo');
expect(toanThayTruong.includes('set search_path = public, pg_temp') && toanThayTruong.includes('proc.prosecdef'), 'Security-definer functions must use a trusted path and explicit execution grants');
for (const column of ['classes\n  add column if not exists portal_id', 'lessons\n  add column if not exists resource_url', 'exams\n  add column if not exists portal_id', 'questions\n  add column if not exists portal_id', 'exam_portal_exams\n  add column if not exists class_id']) expect(classroom.includes(column), `Missing portal classroom column: ${column}`);
for (const helper of ['private.can_access_portal_class', 'private.can_manage_portal_class', 'private.portal_class_member_valid', 'private.portal_exam_payload_valid', 'private.portal_exam_question_valid']) expect(classroom.includes(helper), `Missing classroom RLS helper ${helper}`);
for (const policy of ['classes_portal_manager_write', 'class_students_portal_manager_write', 'lessons_portal_manager_write', 'exams_portal_manager_insert', 'questions_portal_manager_insert', 'exam_questions_portal_manager_write', 'exam_portal_exams_manager_insert']) expect(classroom.includes(policy), `Missing classroom write policy ${policy}`);
expect(classroom.includes('assignment.class_id is null') && classroom.includes('cs.student_id = (select auth.uid())'), 'Portal exams must be scoped to assigned classes');
for (const table of ['classes', 'lessons', 'exams', 'questions', 'exam_questions']) expect(classroomHardening.includes(`on public.${table} as restrictive for all`), `Portal-only write isolation is missing for ${table}`);
expect(classroomHardening.includes('not (select private.is_portal_only_user())'), 'Normal VinhMath and portal-only authoring scopes must stay separate');
expect(classroomReturningFix.includes('private.can_manage_exam_portal(portal_id)') && classroomReturningFix.includes('private.portal_exam_payload_valid(portal_id, class_id)'), 'Hardened INSERT RETURNING path must authorize the portal row directly');
expect(unifiedMigration.includes('exam_focus_mode boolean not null default false') && unifiedMigration.includes("experience_mode<>'full_site'"), 'Exam focus must remain separate from the legacy exam-only portal mode');
expect(unifiedMigration.includes('create or replace function public.vm_admin_deploy_tenant') && unifiedMigration.includes('create or replace function public.vm_admin_update_tenant_lifecycle'), 'Unified tenant publishing must use explicit deploy/update lifecycle RPCs');
expect(unifiedMigration.includes('create or replace function public.vm_my_feature_access') && unifiedMigration.includes('create table if not exists private.vm_feature_user_rules'), 'Role UX authorization needs effective access plus per-user overrides');
expect(!/service_role|SUPABASE_SERVICE_ROLE_KEY/i.test([menu, shared, portal, portalAdmin, exam, examAdmin, migration, hardening, loginSuffix, teacherSuffix, toanThayTruong, classroom, classroomHardening, classroomReturningFix].join('\n')), 'Privileged credentials must not appear in browser or migration files');

console.log('PASS role UX + partner exam portal: navigation, routing, allow-list, account workflow and RLS');
