const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
const base=(process.env.VM_BASE_URL||'http://127.0.0.1:8765').replace(/\/$/,''),output=process.env.VM_GAME_QA_DIR;
const proof=require('../assets/vmgame/proof-engine');
(async()=>{const browser=await chromium.launch({executablePath:process.env.VM_CHROME_PATH,headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage(),errors=[],failed=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&r.url().startsWith(base))failed.push(r.url()+':'+r.status());});page.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('data:'))external.push(r.url());});const shot=async name=>{if(output){fs.mkdirSync(output,{recursive:true});await page.screenshot({path:path.join(output,name+'.png'),fullPage:false});}};
try{
 await page.goto(base+'/vmgame.html',{waitUntil:'networkidle'});await page.locator('#choose-character').click();assert.equal(await page.locator('.character-card').count(),10);
 for(const id of ['usa','geometry','scholar','japan','china','korea','france','britain','nordic','vietnam','usa']){await page.locator(`[data-character="${id}"]`).click();await page.locator(`[data-select-character="${id}"]`).click();assert(await page.locator('#drawer-wrap').evaluate(e=>e.classList.contains('hidden')));assert((await page.locator('#hero-character').getAttribute('src')).endsWith(id+'.webp'));await page.locator('#choose-character').click();}
 await page.locator('[data-filter="female"]').click();assert.equal(await page.locator('.character-card').count(),5);await page.locator('[data-filter="male"]').click();assert.equal(await page.locator('.character-card').count(),5);await page.keyboard.press('Escape');
 await page.locator('.nav [data-view="build"]').click();await page.locator('[data-build="bridge"]').click();assert.equal(await page.locator('#building-count').innerText(),'1 công trình thử');await page.locator('[data-build="bridge"]').click();assert.equal(await page.locator('#building-count').innerText(),'0 công trình thử');await page.locator('#close-drawer').click();
 for(const id of ['vietnam','japan','china','korea','france','britain','usa','nordic']){await page.locator('#choose-region').click();await page.locator(`[data-region="${id}"]`).click();assert(await page.locator('#drawer-wrap').evaluate(e=>e.classList.contains('hidden')));}
 await page.locator('#choose-region').click();await page.goBack();assert(await page.locator('#drawer-wrap').evaluate(e=>e.classList.contains('hidden')));await page.locator('#settings').click();await page.selectOption('#setting-quality','low');await page.locator('#setting-motion').uncheck();await page.keyboard.press('Escape');assert(await page.locator('body').evaluate(e=>e.classList.contains('motion-off')));await page.reload();assert(await page.locator('body').evaluate(e=>e.classList.contains('low-quality')));await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#motion').click();assert(await page.locator('body').evaluate(e=>e.classList.contains('motion-off')));await page.emulateMedia({reducedMotion:'no-preference'});
 await page.locator('.mission-link').click();await page.waitForURL('**/vmgame-proof.html');assert.equal(await page.locator('#progress-count').innerText(),'0 / 6');
 await page.locator('[data-check="goal"]').click();assert((await page.locator('#feedback-goal').innerText()).includes('điền cả'));await page.selectOption('#goal-statement','wrong-goal');await page.selectOption('#goal-theorem','pythagoras');await page.locator('[data-check="goal"]').click();assert((await page.locator('#feedback-goal').innerText()).includes('xem lại'));await page.locator('[data-hint="goal"]').click();assert(await page.locator('#hint-goal').isVisible());
 // Tap-to-place and native select are both functional, with no drag-only requirement.
 await page.locator('#bank-cards [data-card="ratio-equal"]').click();await page.locator('[data-place="statement"][data-step="goal"]').click();assert.equal(await page.locator('#goal-statement').inputValue(),'ratio-equal');
 await page.locator('#bank-goal summary').click();await page.locator('#bank-goal [data-card="converse"]').dragTo(page.locator('#step-goal [data-slot="theorem"] label')); assert.equal(await page.locator('#goal-theorem').inputValue(),'converse');
 for(const step of proof.steps){await page.selectOption('#'+step.id+'-statement',step.statement);await page.selectOption('#'+step.id+'-theorem',step.theorem);await page.locator(`[data-check="${step.id}"]`).click();assert(await page.locator('#step-'+step.id).evaluate(e=>e.classList.contains('verified')));}
 assert.equal(await page.locator('#progress-count').innerText(),'6 / 6');await page.locator('#solution-button').click();assert((await page.locator('.solution').innerText()).includes('Qua E'));assert((await page.locator('.solution-end').innerText()).includes('HF ∥ AC'));await page.keyboard.press('Escape');assert(await page.locator('#solution-button').evaluate(e=>document.activeElement===e));
 await page.reload();assert.equal(await page.locator('#progress-count').innerText(),'6 / 6');await page.selectOption('#goal-statement','wrong-goal');assert.equal(await page.locator('#progress-count').innerText(),'5 / 6');assert(await page.locator('#completion').isHidden());await page.selectOption('#goal-statement','ratio-equal');await page.locator('[data-check="goal"]').click();assert.equal(await page.locator('#progress-count').innerText(),'6 / 6');
 for(const value of ['5','60','95']){await page.locator('#point-g').fill(value);assert.equal(await page.locator('#g-position').innerText(),value+'%');assert.equal(await page.locator('.point-K').count(),1);assert.equal(await page.locator('.target-line').count(),1);}
 await page.locator('#show-auxiliary').uncheck();assert.equal(await page.locator('.point-K').count(),0);await page.locator('#show-auxiliary').check();await page.locator('#show-target').uncheck();assert.equal(await page.locator('.target-line').count(),0);await page.locator('#show-target').check();await page.locator('#point-g').fill('60');
 await page.locator('#expand-figure').click();assert.equal(await page.locator('dialog .point-K').count(),1);await page.locator('#close-dialog').click();await page.locator('#help-button').click();await page.keyboard.press('Escape');
 await page.locator('#reset-button').click();await page.locator('#cancel-reset').click();assert.equal(await page.locator('#progress-count').innerText(),'6 / 6');await page.locator('#reset-button').click();await page.locator('#confirm-reset').click();assert.equal(await page.locator('#progress-count').innerText(),'0 / 6');
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:width<600?844:1000});for(const route of ['vmgame.html','vmgame-proof.html']){await page.goto(base+'/'+route,{waitUntil:'networkidle'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${route} overflow at ${width}`);if(width===390||width===1440)await shot(route.replace('.html','')+'-'+width);if(route==='vmgame.html'){await page.locator('#choose-character').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('#drawer-body').screenshot(output?{path:path.join(output,'roster-'+width+'.png')}:{path:path.join(require('os').tmpdir(),'vmgame-roster-'+width+'.png')});await page.keyboard.press('Escape');}}}
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);assert.deepEqual(external,[]);
 // Real touch context and keyboard operation, independent of drag support.
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const touch=await mobile.newPage();await touch.goto(base+'/vmgame.html');await touch.locator('#choose-character').tap();await touch.locator('[data-character="scholar"]').tap();await touch.locator('[data-select-character="scholar"]').tap();await touch.locator('#choose-region').tap();await touch.locator('[data-region="japan"]').tap();await touch.locator('#settings').tap();await touch.locator('#reset-demo').tap();await touch.locator('#close-drawer').tap();assert((await touch.locator('#hero-character').getAttribute('src')).endsWith('vietnam.webp'));await touch.locator('.mission-link').tap();await touch.locator('#bank-goal summary').tap();await touch.locator('#bank-goal [data-card="ratio-equal"]').tap();await touch.locator('[data-place="statement"][data-step="goal"]').tap();assert.equal(await touch.locator('#goal-statement').inputValue(),'ratio-equal');await mobile.close();
 await page.goto(base+'/vmgame-proof.html');await page.locator('#goal-statement').focus();await page.keyboard.press('Home');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');assert.equal(await page.locator('#goal-statement').inputValue(),proof.statements[0].id);await page.locator('#help-button').focus();await page.keyboard.press('Enter');assert(await page.locator('dialog').isVisible());await page.keyboard.press('Escape');assert(await page.locator('#help-button').evaluate(e=>document.activeElement===e));
 const deny=await browser.newContext();await deny.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw Error('denied')}}));const p=await deny.newPage();await p.goto(base+'/vmgame-proof.html');await p.selectOption('#goal-statement','ratio-equal');await p.selectOption('#goal-theorem','converse');await p.locator('[data-check="goal"]').click();assert.equal(await p.locator('#progress-count').innerText(),'1 / 6');await p.goto(base+'/vmgame.html');await p.locator('#choose-character').click();assert.equal(await p.locator('.character-card').count(),10);await deny.close();
 console.log('PASS VMGame browser: 10 characters/reselection, filters, 8 regions, construction toggle, drawer/back/Escape, persistence, effect/OS reduced motion, proof incorrect/retry/hints/tap/drag/select, all six steps, solution gate, reset/cancel, geometry controls, storage denied, desktop/mobile 320/390/768/1440, no page errors or failed/off-origin requests.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
