from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
report = (ROOT / "quan-tri-bao-cao-hoc-sinh.html").read_text(encoding="utf-8")
students = (ROOT / "quan-tri-hoc-sinh.html").read_text(encoding="utf-8")
classes = (ROOT / "quan-tri-lop.html").read_text(encoding="utf-8")
sql = (ROOT / "web" / "supabase" / "teacher_student_period_report.sql").read_text(encoding="utf-8")
insights_sql = (ROOT / "web" / "supabase" / "teacher_report_insights.sql").read_text(encoding="utf-8")


def require(source: str, fragment: str, message: str) -> None:
    if fragment not in source:
        raise AssertionError(message)


require(students, "quan-tri-bao-cao-hoc-sinh?studentId=", "Danh sách học sinh chưa dẫn tới báo cáo mới")
require(report, "gv_bao_cao_hs", "Báo cáo chưa kiểm tra quyền quản lý học sinh")
require(report, "gv_bao_cao_hoc_tap", "Báo cáo chưa dùng truy vấn tổng hợp có phân quyền")
require(report, "['admin','teacher']", "Báo cáo chưa giới hạn đúng tài khoản giáo viên/quản trị viên")
require(report, 'id="reportGrade"', "Bộ lọc báo cáo chưa có bước chọn khối")
require(report, 'id="reportClass"', "Bộ lọc báo cáo chưa có bước chọn lớp")
require(report, 'id="reportStudent"', "Bộ lọc báo cáo chưa có bước chọn học sinh")
require(report, 'data-period="week"', "Thiếu báo cáo theo tuần lịch")
require(report, 'data-period="month"', "Thiếu báo cáo theo tháng lịch")
require(report, 'id="reportPeriodChoice"', "Thiếu nhãn kỳ báo cáo đang được chọn")
require(report, 'id="reportPeriodPicker"', "Thiếu ô chọn trực tiếp tuần hoặc tháng lịch sử")
require(report, "dichKyBaoCao", "Thiếu điều hướng tuần/tháng trước và sau")
require(report, "chonNgayKyBaoCao", "Ô chọn kỳ lịch sử chưa nối với báo cáo")
require(report, "q.set('anchor'", "Liên kết báo cáo chưa ghi nhớ kỳ lịch sử đã chọn")
require(report, "new Date(year,month+1,0)", "Tháng chưa kết thúc đúng ngày cuối cùng")
require(report, "mondayOffset", "Tuần chưa bắt đầu từ thứ Hai")
require(report, "data-export-exclude", "Chưa đánh dấu nội dung loại khỏi ảnh xuất")
require(report, "onclone", "Xuất ảnh chưa loại nội dung riêng của giáo viên")
require(report, "cloneNode(true)", "Xuất ảnh chưa dùng bản sao bố cục cố định")
require(report, "document.fonts.ready", "Xuất ảnh chưa đợi font hoàn tất trước khi dựng PNG")
require(report, "card.getBoundingClientRect()", "Xuất ảnh chưa đo kích thước khung ngoài nên có thể bị hụt viền")
require(report, ".report-sheet.exporting .metric-grid", "Ảnh xuất chưa khóa lưới chỉ số độc lập với màn hình")
require(report, ".report-sheet.exporting .student-avatar", "Ảnh xuất chưa khóa căn giữa chữ viết tắt học sinh")
require(report, 'id="reportStrengths"', "Nhận định chưa có mục Ưu điểm riêng")
require(report, 'id="reportLimitations"', "Nhận định chưa có mục Hạn chế riêng")
require(report, 'id="reportImprovements"', "Nhận định chưa có mục Cần cải thiện riêng")
require(report, 'id="btnEditInsights"', "Nhận định chưa có nút chỉnh sửa trực tiếp")
require(report, 'id="editStrengths"', "Trình chỉnh sửa chưa có mục Ưu điểm")
require(report, 'id="editLimitations"', "Trình chỉnh sửa chưa có mục Hạn chế")
require(report, 'id="editImprovements"', "Trình chỉnh sửa chưa có mục Cần cải thiện")
require(report, "teacher_report_insights", "Báo cáo chưa đọc và lưu nhận định giáo viên theo kỳ")
require(report, "upsert(row", "Nút lưu chưa ghi nhận định giáo viên")
require(report, "reportInsightDirty", "Xuất ảnh chưa bảo vệ thay đổi nhận định chưa lưu")
require(report, "Ảnh tải xuống sẽ dùng nội dung này", "Giao diện chưa xác nhận bản lưu được dùng trong ảnh xuất")
require(report, 'id="rowHomeworkSubmitted"', "Chi tiết chưa nêu số BTVN bắt buộc đã nộp")
require(report, 'id="rowHomeworkOnTime"', "Chi tiết chưa nêu số BTVN bắt buộc đúng hạn")
require(report, 'id="rowHomeworkReviewed"', "Chi tiết BTVN bắt buộc chưa có số bài chấm đã xem lại")
require(report, 'id="rowBonusSubmitted"', "Chi tiết chưa tách số BT thưởng đã nộp")
require(report, 'id="rowBonusOnTime"', "Chi tiết chưa tách số BT thưởng đúng hạn")
require(report, 'id="rowBonusReviewed"', "Chi tiết BT thưởng chưa có số bài chấm đã xem lại")
require(report, 'class="detail-group-title"><span>1</span>Chuyên cần', "Chi tiết chưa gom nhóm Chuyên cần")
require(report, 'class="detail-group-title"><span>2</span>BTVN bắt buộc', "Chi tiết chưa gom nhóm BTVN bắt buộc")
require(report, 'class="detail-group-title"><span>3</span>BT thưởng thêm', "Chi tiết chưa gom nhóm BT thưởng thêm")
if 'id="rowScoreDetail"' in report or 'id="rowTests"' in report:
    raise AssertionError("Chi tiết trong kỳ vẫn còn mục kết quả điểm hoặc bài kiểm tra ngoài cấu trúc mới")
require(report, "📥 Tải ảnh báo cáo", "Nút tải ảnh chưa dùng biểu tượng tải xuống phù hợp")
require(classes, "quan-tri-bao-cao-hoc-sinh?classId=", "Danh sách lớp chưa có phím tắt báo cáo cho từng học sinh")
require(classes, "studentId=", "Phím tắt trong lớp chưa truyền đúng học sinh")
require(sql, "lesson_item_progress", "Thiếu chỉ số xem bài")
require(sql, "homework_due", "Bài nộp chưa dùng hạn BTVN thực tế")
require(sql, "homework2_due", "Bài thưởng chưa được phân luồng riêng")
require(sql, "test_deadline", "Bài kiểm tra chưa dùng hạn thực tế")
require(sql, "linked_exam_id", "Báo cáo chưa tính bài luyện đề được liên kết")
require(sql, "is_late", "Thiếu chỉ số nộp đúng hạn")
require(sql, "reviewed_at", "RPC chưa trả trạng thái học sinh xem lại bài đã chấm")
require(sql, "graded_at", "RPC chưa trả trạng thái bài đã được chấm")
require(sql, "feedback", "RPC chưa trả dữ liệu xác định bài đã có lời phê")
require(sql, "analytics_sessions", "Thiếu thời gian hoạt động web")
require(sql, "study_sessions", "Thiếu thời gian tự học có chủ đích")
require(sql, "s.submitted_at < v_end_at", "Báo cáo cũ vẫn có thể bị thay đổi bởi bài nộp sau kỳ")
require(sql, "a.submitted_at < v_end_at", "Lượt làm bài sau kỳ vẫn có thể bị tính vào báo cáo")
require(report, "html2canvas", "Thiếu chức năng xuất ảnh")
require(report, "windowWidth:1200", "Xuất ảnh chưa khóa khung dựng độc lập với màn hình thiết bị")
require(report, ".report-sheet.exporting *{animation:none!important", "Xuất ảnh chưa vô hiệu hóa hiệu ứng làm lệch thời điểm chụp")
require(report, '[data-theme="dark"] .report-sheet:not(.exporting)', "Báo cáo chưa có giao diện tối theo hệ thống")
require(report, '[data-theme="dark"] .report-sheet:not(.exporting) .insight-editor-field textarea', "Trình sửa nhận định chưa hỗ trợ giao diện tối")
require(report, "navigator.share", "Thiếu chức năng chia sẻ ảnh trên điện thoại")
require(report, "@media(max-width:620px)", "Báo cáo chưa tối ưu giao diện điện thoại")
require(sql, "security definer", "RPC báo cáo chưa khai báo ngữ cảnh bảo mật")
require(sql, "set search_path = ''", "RPC báo cáo chưa khóa search_path")
require(sql, "auth.uid()", "RPC báo cáo chưa xác thực người gọi")
require(sql, "v_role is null", "RPC báo cáo chưa chặn tài khoản thiếu hồ sơ/quyền")
require(sql, "can_manage_class", "RPC báo cáo chưa giới hạn lớp giáo viên quản lý")
require(sql, "coalesce(public.can_manage_class", "RPC báo cáo có thể bỏ lọt kết quả quyền NULL")
require(sql, "student_not_in_class", "RPC báo cáo chưa xác nhận học sinh thuộc lớp")
require(sql, "revoke all", "RPC báo cáo chưa thu hồi quyền gọi mặc định")
require(sql, "grant execute", "RPC báo cáo chưa cấp quyền rõ cho authenticated")
require(insights_sql, "create table if not exists public.teacher_report_insights", "Thiếu bảng lưu nhận định giáo viên")
require(insights_sql, "enable row level security", "Bảng nhận định chưa bật RLS")
require(insights_sql, "revoke all on table public.teacher_report_insights from anon", "Bảng nhận định chưa chặn anon")
require(insights_sql, "grant select, insert, update", "Bảng nhận định chưa giới hạn đúng thao tác cho authenticated")
require(insights_sql, "coalesce(public.can_manage_class", "RLS nhận định chưa giới hạn đúng giáo viên phụ trách lớp")
require(insights_sql, "coalesce(public.is_admin", "RLS nhận định chưa cho phép quản trị viên đúng cách")
require(insights_sql, "from public.class_students", "RLS nhận định chưa xác nhận học sinh thuộc lớp")
require(insights_sql, "edited_by = (select auth.uid())", "RLS nhận định chưa khóa người chỉnh theo phiên đăng nhập")
require(insights_sql, "teacher_report_insights_class_id_idx", "Bảng nhận định chưa có chỉ mục cho lớp")
require(insights_sql, "teacher_report_insights_edited_by_idx", "Bảng nhận định chưa có chỉ mục cho giáo viên chỉnh sửa")

print("PASS teacher student period report regression checks")
