-- VinhMath: centralized TeX environment registry for web reader and PDF renderer.
-- Public users may only read published definitions. Drafts, history and publishing
-- are restricted to authenticated administrators through RLS and guarded RPCs.

create table if not exists public.tex_environment_configs (
  environment_name text primary key check (environment_name ~ '^[a-zA-Z][a-zA-Z0-9@_-]{0,63}$'),
  display_name text not null,
  aliases text[] not null default '{}',
  icon text not null default '📘',
  tone text not null default 'definition' check (tone in ('definition','theorem','example','note','remark','practice','form','summary')),
  is_numbered boolean not null default false,
  counter_group text,
  web_config jsonb not null default '{}'::jsonb check (jsonb_typeof(web_config) = 'object'),
  latex_definition text not null default '' check (octet_length(latex_definition) <= 200000),
  sample_latex text not null default '' check (octet_length(sample_latex) <= 200000),
  version integer not null default 1 check (version > 0),
  published_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.tex_environment_drafts (
  environment_name text primary key check (environment_name ~ '^[a-zA-Z][a-zA-Z0-9@_-]{0,63}$'),
  display_name text not null,
  aliases text[] not null default '{}',
  icon text not null default '📘',
  tone text not null default 'definition' check (tone in ('definition','theorem','example','note','remark','practice','form','summary')),
  is_numbered boolean not null default false,
  counter_group text,
  web_config jsonb not null default '{}'::jsonb check (jsonb_typeof(web_config) = 'object'),
  latex_definition text not null default '' check (octet_length(latex_definition) <= 200000),
  sample_latex text not null default '' check (octet_length(sample_latex) <= 200000),
  base_version integer not null default 0 check (base_version >= 0),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.tex_environment_versions (
  id bigint generated by default as identity primary key,
  environment_name text not null,
  version integer not null check (version > 0),
  snapshot jsonb not null,
  published_at timestamptz not null default now(),
  published_by uuid references auth.users(id) on delete set null,
  unique (environment_name, version)
);

create index if not exists tex_environment_versions_env_idx
  on public.tex_environment_versions (environment_name, version desc);

alter table public.tex_environment_configs enable row level security;
alter table public.tex_environment_drafts enable row level security;
alter table public.tex_environment_versions enable row level security;

drop policy if exists tex_environment_configs_read on public.tex_environment_configs;
create policy tex_environment_configs_read
  on public.tex_environment_configs for select to anon, authenticated
  using (true);

drop policy if exists tex_environment_configs_admin_write on public.tex_environment_configs;

drop policy if exists tex_environment_drafts_admin on public.tex_environment_drafts;
create policy tex_environment_drafts_admin
  on public.tex_environment_drafts for all to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

drop policy if exists tex_environment_versions_admin on public.tex_environment_versions;
create policy tex_environment_versions_admin
  on public.tex_environment_versions for all to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

revoke all on public.tex_environment_configs from anon, authenticated;
revoke all on public.tex_environment_drafts from anon, authenticated;
revoke all on public.tex_environment_versions from anon, authenticated;
grant select on public.tex_environment_configs to anon, authenticated;
grant select, insert, update, delete on public.tex_environment_drafts to authenticated;
grant select on public.tex_environment_versions to authenticated;

create or replace function public.stamp_tex_environment_draft()
returns trigger
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  new.updated_at := now();
  new.updated_by := auth.uid();
  return new;
end;
$$;

drop trigger if exists stamp_tex_environment_draft on public.tex_environment_drafts;
create trigger stamp_tex_environment_draft
before insert or update on public.tex_environment_drafts
for each row execute function public.stamp_tex_environment_draft();

create or replace function public.publish_tex_environment(p_environment_name text)
returns public.tex_environment_configs
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  d public.tex_environment_drafts%rowtype;
  current_version integer;
  result public.tex_environment_configs%rowtype;
begin
  if auth.uid() is null or not public.is_admin() then
    raise exception 'Administrator permission required' using errcode = '42501';
  end if;

  select * into d
  from public.tex_environment_drafts
  where environment_name = p_environment_name
  for update;

  if not found then
    raise exception 'Draft environment % does not exist', p_environment_name using errcode = 'P0002';
  end if;

  if exists (
    select 1 from public.tex_environment_configs c
    where c.environment_name <> d.environment_name
      and (
        c.environment_name = any(d.aliases)
        or d.environment_name = any(c.aliases)
        or c.aliases && d.aliases
      )
  ) then
    raise exception 'Environment name or alias is already in use' using errcode = '23505';
  end if;

  select coalesce(version, 0) into current_version
  from public.tex_environment_configs
  where environment_name = p_environment_name
  for update;
  current_version := coalesce(current_version, 0) + 1;

  insert into public.tex_environment_configs (
    environment_name, display_name, aliases, icon, tone, is_numbered,
    counter_group, web_config, latex_definition, sample_latex, version,
    published_at, updated_at, updated_by
  ) values (
    d.environment_name, d.display_name, d.aliases, d.icon, d.tone, d.is_numbered,
    nullif(d.counter_group, ''), d.web_config, d.latex_definition, d.sample_latex,
    current_version, now(), now(), auth.uid()
  )
  on conflict (environment_name) do update set
    display_name = excluded.display_name,
    aliases = excluded.aliases,
    icon = excluded.icon,
    tone = excluded.tone,
    is_numbered = excluded.is_numbered,
    counter_group = excluded.counter_group,
    web_config = excluded.web_config,
    latex_definition = excluded.latex_definition,
    sample_latex = excluded.sample_latex,
    version = excluded.version,
    published_at = excluded.published_at,
    updated_at = excluded.updated_at,
    updated_by = excluded.updated_by
  returning * into result;

  insert into public.tex_environment_versions (
    environment_name, version, snapshot, published_at, published_by
  ) values (
    result.environment_name,
    result.version,
    to_jsonb(result) - 'updated_by',
    result.published_at,
    auth.uid()
  ) on conflict (environment_name, version) do nothing;

  update public.tex_environment_drafts
  set base_version = result.version, updated_at = now(), updated_by = auth.uid()
  where environment_name = p_environment_name;

  return result;
end;
$$;

create or replace function public.restore_tex_environment_version(
  p_environment_name text,
  p_version integer
)
returns public.tex_environment_drafts
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v jsonb;
  result public.tex_environment_drafts%rowtype;
begin
  if auth.uid() is null or not public.is_admin() then
    raise exception 'Administrator permission required' using errcode = '42501';
  end if;

  select snapshot into v
  from public.tex_environment_versions
  where environment_name = p_environment_name and version = p_version;

  if v is null then
    raise exception 'Version %.% does not exist', p_environment_name, p_version using errcode = 'P0002';
  end if;

  insert into public.tex_environment_drafts (
    environment_name, display_name, aliases, icon, tone, is_numbered,
    counter_group, web_config, latex_definition, sample_latex,
    base_version, updated_at, updated_by
  ) values (
    p_environment_name,
    v->>'display_name',
    coalesce(array(select jsonb_array_elements_text(coalesce(v->'aliases', '[]'::jsonb))), '{}'),
    coalesce(v->>'icon', '📘'),
    coalesce(v->>'tone', 'definition'),
    coalesce((v->>'is_numbered')::boolean, false),
    nullif(v->>'counter_group', ''),
    coalesce(v->'web_config', '{}'::jsonb),
    coalesce(v->>'latex_definition', ''),
    coalesce(v->>'sample_latex', ''),
    p_version,
    now(), auth.uid()
  )
  on conflict (environment_name) do update set
    display_name = excluded.display_name,
    aliases = excluded.aliases,
    icon = excluded.icon,
    tone = excluded.tone,
    is_numbered = excluded.is_numbered,
    counter_group = excluded.counter_group,
    web_config = excluded.web_config,
    latex_definition = excluded.latex_definition,
    sample_latex = excluded.sample_latex,
    base_version = excluded.base_version,
    updated_at = excluded.updated_at,
    updated_by = excluded.updated_by
  returning * into result;

  return result;
end;
$$;

revoke all on function public.publish_tex_environment(text) from public, anon;
revoke all on function public.restore_tex_environment_version(text, integer) from public, anon;
revoke all on function public.stamp_tex_environment_draft() from public, anon, authenticated;
grant execute on function public.publish_tex_environment(text) to authenticated;
grant execute on function public.restore_tex_environment_version(text, integer) to authenticated;

with seed(environment_name, display_name, aliases, icon, tone, is_numbered, counter_group, web_config, sample_latex) as (
  values
    ('boxdn','Định nghĩa',array['mydn','dn'],'📗','definition',false,null,
      '{"accent":"#158466","background":"#f0fbf6","border":"#b9e6d4","title_background":"#e2f4ec","dark_background":"#0d2922","dark_border":"#285c4d","dark_title_background":"#13372e","radius":"14px","border_width":"2px"}'::jsonb,
      '\\begin{boxdn}Hai tập hợp bằng nhau khi chúng có cùng các phần tử.\\end{boxdn}'),
    ('boxdl','Định lý',array['mydl','dl'],'📐','theorem',false,null,
      '{"accent":"#3156a6","background":"#f2f6ff","border":"#c8d5f4","title_background":"#e7eefc","dark_background":"#151f38","dark_border":"#354c7f","dark_title_background":"#1b2949","radius":"14px","border_width":"2px"}'::jsonb,
      '\\begin{boxdl}Nếu hai đường thẳng cùng vuông góc với một đường thẳng thì chúng song song.\\end{boxdl}'),
    ('boxvidu','Ví dụ',array['myvidu','vidu','vd'],'🧩','example',true,'example',
      '{"accent":"#8b5b00","background":"#fff9ed","border":"#ecd7a7","title_background":"#fff1cc","dark_background":"#2b2211","dark_border":"#735a24","dark_title_background":"#3a2b10","radius":"14px","border_width":"2px"}'::jsonb,
      '\\begin{boxvidu}Tính $A=1+2+3$.\\end{boxvidu}'),
    ('luuy','Lưu ý',array['note','makerr'],'💡','note',false,null,
      '{"accent":"#d78a00","background":"#fffaf0","border":"#f0d49d","title_background":"#fff0ca","dark_background":"#2b220f","dark_border":"#735421","dark_title_background":"#3b2c10","radius":"14px","border_width":"2px"}'::jsonb,
      '\\begin{luuy}Kiểm tra điều kiện xác định trước khi biến đổi.\\end{luuy}'),
    ('nx','Nhận xét',array['remark','boxtb'],'💬','remark',false,null,
      '{"accent":"#7254a8","background":"#f8f5ff","border":"#d9cef0","title_background":"#eee8fa","dark_background":"#241b36","dark_border":"#5b467d","dark_title_background":"#302344","radius":"14px","border_width":"2px"}'::jsonb,
      '\\begin{nx}Cách giải này ngắn gọn và dễ kiểm tra.\\end{nx}'),
    ('bt','Bài tập',array['ex'],'✍️','practice',true,'exercise',
      '{"accent":"#c46f00","background":"#fffaf2","border":"#efd1a3","title_background":"#ffefd2","dark_background":"#2d2112","dark_border":"#765226","dark_title_background":"#3b2a13","radius":"16px","border_width":"2px"}'::jsonb,
      '\\begin{bt}Giải phương trình $2x+1=5$.\\loigiai{$x=2$.}\\end{bt}'),
    ('dang','Dạng toán',array['dangg','khung4','noidung'],'🧭','form',true,'form',
      '{"accent":"#b45525","background":"#fff6f1","border":"#ebc5b0","title_background":"#fde8dd","dark_background":"#301d16","dark_border":"#704432","dark_title_background":"#3d251b","radius":"16px","border_width":"2px"}'::jsonb,
      '\\begin{dang}{Phương trình bậc nhất}Giải phương trình dạng $ax+b=0$.\\end{dang}'),
    ('tomtat','Tóm tắt',array['tttt'],'📝','summary',false,null,
      '{"accent":"#54616f","background":"#f6f8fa","border":"#d5dce3","title_background":"#edf1f5","dark_background":"#1d2329","dark_border":"#46515c","dark_title_background":"#252d35","radius":"14px","border_width":"1px"}'::jsonb,
      '\\begin{tomtat}Các ý chính của bài học được hệ thống tại đây.\\end{tomtat}')
)
insert into public.tex_environment_configs (
  environment_name, display_name, aliases, icon, tone, is_numbered,
  counter_group, web_config, sample_latex, latex_definition, version
)
select environment_name, display_name, aliases, icon, tone, is_numbered,
       counter_group, web_config, sample_latex, '', 1
from seed
on conflict (environment_name) do nothing;

insert into public.tex_environment_drafts (
  environment_name, display_name, aliases, icon, tone, is_numbered,
  counter_group, web_config, latex_definition, sample_latex, base_version
)
select environment_name, display_name, aliases, icon, tone, is_numbered,
       counter_group, web_config, latex_definition, sample_latex, version
from public.tex_environment_configs
on conflict (environment_name) do nothing;

insert into public.tex_environment_versions (
  environment_name, version, snapshot, published_at, published_by
)
select environment_name, version, to_jsonb(c) - 'updated_by', published_at, updated_by
from public.tex_environment_configs c
on conflict (environment_name, version) do nothing;
