-- Unified tenant lifecycle, system appearance defaults and server-enforced
-- feature permissions.  Tenant feature rules remain presentation-only; the
-- private feature policy below is the authorization source of truth.

alter table public.exam_portals
  add column if not exists exam_focus_mode boolean not null default false,
  add column if not exists deployed_at timestamptz,
  add column if not exists deployed_by uuid references public.profiles(id) on delete set null;

comment on column public.exam_portals.exam_focus_mode is
  'Presentation state for a full-site tenant. It focuses navigation on exams without changing experience_mode or authorization.';

insert into public.app_settings(key,value) values
  ('theme_mode','schedule'),
  ('theme_light_start','06:00'),
  ('theme_dark_start','19:00')
on conflict (key) do nothing;

do $do$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='app_settings'
  ) then
    alter publication supabase_realtime add table public.app_settings;
  end if;
end;
$do$;

create table if not exists private.vm_feature_catalog (
  feature_key text primary key,
  parent_key text references private.vm_feature_catalog(feature_key) on delete restrict,
  kind text not null default 'route' check (kind in ('route','capability','system')),
  label text not null,
  description text not null default '',
  group_key text not null default 'general',
  sort_order integer not null default 0,
  default_state text not null default 'hidden' check (default_state in ('shown','locked','hidden')),
  is_delegable boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vm_feature_catalog_key_check check (feature_key ~ '^[a-z][a-z0-9_.]{1,79}$')
);

create table if not exists private.vm_feature_role_rules (
  role_scope text not null check (role_scope in ('admin','teacher','assistant','student','parent')),
  feature_key text not null references private.vm_feature_catalog(feature_key) on delete cascade,
  state text not null check (state in ('shown','locked','hidden')),
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(),
  primary key(role_scope,feature_key)
);

create table if not exists private.vm_feature_user_rules (
  user_id uuid not null references public.profiles(id) on delete cascade,
  feature_key text not null references private.vm_feature_catalog(feature_key) on delete cascade,
  state text not null check (state in ('shown','locked','hidden')),
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(),
  primary key(user_id,feature_key)
);

create table if not exists private.vm_feature_policy_audit (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  target_role text,
  target_user_id uuid references public.profiles(id) on delete set null,
  feature_key text,
  action text not null,
  previous_state text,
  next_state text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists vm_feature_policy_audit_target_idx
  on private.vm_feature_policy_audit(target_user_id,created_at desc);

revoke all on table private.vm_feature_catalog from public,anon,authenticated;
revoke all on table private.vm_feature_role_rules from public,anon,authenticated;
revoke all on table private.vm_feature_user_rules from public,anon,authenticated;
revoke all on table private.vm_feature_policy_audit from public,anon,authenticated;

insert into private.vm_feature_catalog
  (feature_key,parent_key,kind,label,description,group_key,sort_order,default_state,is_delegable)
values
  ('home',null,'route','Hôm nay','Trang tổng quan','navigation',10,'shown',true),
  ('classes',null,'route','Lớp học','Không gian lớp học','navigation',20,'hidden',true),
  ('grading',null,'route','Chấm bài','Chấm và trả bài','navigation',30,'hidden',true),
  ('authoring',null,'route','Soạn thảo','Soạn tài liệu và đề','navigation',40,'hidden',true),
  ('schedule',null,'route','Lịch','Lịch dạy và học','navigation',50,'hidden',true),
  ('vmtool',null,'route','VMTool','Công cụ Toán học','navigation',60,'hidden',true),
  ('profile',null,'route','Cá nhân','Hồ sơ cá nhân','navigation',70,'shown',true),
  ('lessons',null,'route','Bài học','Kho bài học','navigation',80,'hidden',true),
  ('practice',null,'route','Luyện tập','Bài tập và đề luyện','navigation',90,'hidden',true),
  ('results',null,'route','Kết quả','Kết quả học tập','navigation',100,'hidden',true),
  ('leaderboard',null,'route','Xếp hạng','Bảng xếp hạng','navigation',110,'hidden',true),
  ('parental',null,'route','Phụ huynh','Theo dõi học tập','navigation',120,'hidden',true),
  ('admin',null,'route','Quản trị','Trung tâm quản trị','navigation',130,'hidden',false),
  ('question_bank',null,'route','Ngân hàng đề','Dùng ngân hàng đề','question_bank',200,'hidden',true),
  ('question_bank.use','question_bank','capability','Sử dụng ngân hàng','Tìm, xem trước và tạo đề','question_bank',210,'hidden',true),
  ('question_bank.report','question_bank','capability','Báo lỗi nội dung','Gửi lỗi về quản trị viên','question_bank',220,'hidden',true),
  ('question_bank.import_tex','question_bank','capability','Nạp TeX','Nạp nguồn TeX vào hàng chờ duyệt','question_bank',230,'hidden',true),
  ('question_bank.download_tex','question_bank','capability','Tải TeX','Tải nguyên liệu TeX có kiểm toán','question_bank',240,'hidden',true),
  ('question_bank.manage','question_bank','capability','Quản lý kho','Duyệt, sửa và quản lý nguồn; chỉ quản trị viên','question_bank',250,'hidden',false),
  ('question_bank.id_schema_manage','question_bank','system','Quản lý hệ ID','Tạo và chuyển đổi hệ ID','question_bank',260,'hidden',false),
  ('feature_policy.manage',null,'system','Quản lý quyền','Quản lý chính sách tính năng','security',300,'hidden',false)
on conflict(feature_key) do update set
  parent_key=excluded.parent_key,
  kind=excluded.kind,
  label=excluded.label,
  description=excluded.description,
  group_key=excluded.group_key,
  sort_order=excluded.sort_order,
  is_delegable=excluded.is_delegable,
  updated_at=now();

insert into private.vm_feature_role_rules(role_scope,feature_key,state)
select role_scope,feature_key,
  case
    when role_scope='admin' then 'shown'
    when role_scope='teacher' and feature_key in (
      'home','classes','grading','authoring','schedule','vmtool','profile',
      'question_bank','question_bank.use','question_bank.report'
    ) then 'shown'
    when role_scope='assistant' and feature_key in ('home','classes','grading','schedule','profile') then 'shown'
    when role_scope='student' and feature_key in ('home','lessons','practice','results','leaderboard','vmtool','profile') then 'shown'
    when role_scope='parent' and feature_key in ('home','parental','results','profile') then 'shown'
    else 'hidden'
  end
from (values('admin'),('teacher'),('assistant'),('student'),('parent')) r(role_scope)
cross join private.vm_feature_catalog c
on conflict(role_scope,feature_key) do nothing;

create or replace function private.vm_effective_feature_state(
  p_user_id uuid,
  p_feature_key text
)
returns text
language plpgsql
stable
security definer
set search_path=''
as $function$
declare
  v_role text;
  v_state text;
begin
  select role into v_role from public.profiles where id=p_user_id;
  if v_role is null then return 'hidden'; end if;
  if v_role='admin' then return 'shown'; end if;

  select rule.state into v_state
  from private.vm_feature_user_rules rule
  where rule.user_id=p_user_id and rule.feature_key=p_feature_key;
  if found then return v_state; end if;

  select rule.state into v_state
  from private.vm_feature_role_rules rule
  where rule.role_scope=v_role and rule.feature_key=p_feature_key;
  if found then return v_state; end if;

  select catalog.default_state into v_state
  from private.vm_feature_catalog catalog
  where catalog.feature_key=p_feature_key;
  return coalesce(v_state,'hidden');
end;
$function$;

create or replace function private.vm_has_feature(p_user_id uuid,p_feature_key text)
returns boolean
language sql
stable
security definer
set search_path=''
as $function$
  select case
    when p_user_id is null then false
    when public.is_admin() and p_user_id=(select auth.uid()) then true
    else private.vm_effective_feature_state(p_user_id,p_feature_key)='shown'
  end;
$function$;

revoke all on function private.vm_effective_feature_state(uuid,text) from public,anon,authenticated;
revoke all on function private.vm_has_feature(uuid,text) from public,anon,authenticated;

create or replace function public.vm_my_feature_access(p_portal_id uuid default null)
returns jsonb
language plpgsql
stable
security definer
set search_path=''
as $function$
declare
  v_uid uuid:=(select auth.uid());
  v_role text;
  v_member_role text;
  v_items jsonb;
begin
  if v_uid is null then raise exception 'authentication_required' using errcode='42501'; end if;
  select role into v_role from public.profiles where id=v_uid;
  if v_role is null then raise exception 'profile_required' using errcode='42501'; end if;
  if p_portal_id is not null and v_role<>'admin' then
    select m.member_role into v_member_role
    from public.exam_portal_members m
    join public.exam_portals p on p.id=m.portal_id
    where m.portal_id=p_portal_id
      and m.user_id=v_uid
      and p.is_active
      and p.experience_mode='full_site';
    if not found then p_portal_id:=null; end if;
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'feature_key',c.feature_key,
    'state',case
      when global_state='hidden' or tenant_state='hidden' then 'hidden'
      when global_state='locked' or tenant_state='locked' then 'locked'
      else 'shown' end,
    'source',case when tenant_state<>'shown' then 'portal' when u.feature_key is not null then 'user' else 'role' end
  ) order by c.sort_order,c.feature_key),'[]'::jsonb)
  into v_items
  from private.vm_feature_catalog c
  left join private.vm_feature_user_rules u on u.user_id=v_uid and u.feature_key=c.feature_key
  cross join lateral (select private.vm_effective_feature_state(v_uid,c.feature_key) global_state) g
  cross join lateral (
    select coalesce((
      select r.state from public.exam_portal_feature_rules r
      where r.portal_id=p_portal_id and r.feature_key=c.feature_key
        and (r.role_scope='*' or r.role_scope=v_role or r.role_scope=v_member_role)
      order by case
        when v_member_role is not null and r.role_scope=v_member_role then 0
        when r.role_scope=v_role then 1
        else 2
      end,r.updated_at desc limit 1
    ),'shown') tenant_state
  ) t;

  return jsonb_build_object(
    'items',v_items,
    'bank',jsonb_build_object(
      'can_use',private.vm_has_feature(v_uid,'question_bank.use'),
      'can_report',private.vm_has_feature(v_uid,'question_bank.report'),
      'can_import',private.vm_has_feature(v_uid,'question_bank.import_tex'),
      'can_download_tex',private.vm_has_feature(v_uid,'question_bank.download_tex'),
      'can_manage',private.vm_has_feature(v_uid,'question_bank.manage'),
      'can_manage_id_schema',private.vm_has_feature(v_uid,'question_bank.id_schema_manage'),
      'is_admin',v_role='admin'
    )
  );
end;
$function$;

create or replace function public.vm_my_bank_capabilities()
returns jsonb
language sql
stable
security definer
set search_path=''
as $function$
  select coalesce(public.vm_my_feature_access(null)->'bank','{}'::jsonb);
$function$;

create or replace function public.vm_admin_feature_matrix(p_user_id uuid default null)
returns jsonb
language plpgsql
stable
security definer
set search_path=''
as $function$
begin
  if (select auth.uid()) is null or not (select public.is_admin()) then
    raise exception 'admin_required' using errcode='42501';
  end if;
  return jsonb_build_object(
    'catalog',coalesce((select jsonb_agg(to_jsonb(c) order by c.group_key,c.sort_order,c.feature_key) from private.vm_feature_catalog c),'[]'::jsonb),
    'role_rules',coalesce((select jsonb_agg(to_jsonb(r) order by r.role_scope,c.sort_order) from private.vm_feature_role_rules r join private.vm_feature_catalog c using(feature_key)),'[]'::jsonb),
    'user_rules',coalesce((select jsonb_agg(to_jsonb(u) order by c.sort_order) from private.vm_feature_user_rules u join private.vm_feature_catalog c using(feature_key) where u.user_id=p_user_id),'[]'::jsonb),
    'effective',coalesce((select jsonb_agg(jsonb_build_object('feature_key',c.feature_key,'state',private.vm_effective_feature_state(p_user_id,c.feature_key)) order by c.sort_order) from private.vm_feature_catalog c where p_user_id is not null),'[]'::jsonb)
  );
end;
$function$;

create or replace function public.vm_admin_save_role_feature_rules(p_role text,p_rules jsonb)
returns jsonb
language plpgsql
volatile
security definer
set search_path=''
as $function$
declare v_actor uuid:=(select auth.uid()); v_item jsonb; v_previous text;
begin
  if v_actor is null or not (select public.is_admin()) then raise exception 'admin_required' using errcode='42501'; end if;
  if p_role not in ('teacher','assistant','student','parent') or p_rules is null or jsonb_typeof(p_rules) is distinct from 'array' then raise exception 'feature_rules_invalid' using errcode='22023'; end if;
  for v_item in select value from jsonb_array_elements(p_rules) loop
    if coalesce(v_item->>'feature_key','')='' or coalesce(v_item->>'state','') not in ('shown','locked','hidden')
      or not exists(select 1 from private.vm_feature_catalog c where c.feature_key=v_item->>'feature_key' and c.is_delegable) then
      raise exception 'feature_rule_invalid' using errcode='22023';
    end if;
    select state into v_previous from private.vm_feature_role_rules where role_scope=p_role and feature_key=v_item->>'feature_key';
    insert into private.vm_feature_role_rules(role_scope,feature_key,state,updated_by,updated_at)
    values(p_role,v_item->>'feature_key',v_item->>'state',v_actor,now())
    on conflict(role_scope,feature_key) do update set state=excluded.state,updated_by=excluded.updated_by,updated_at=excluded.updated_at;
    insert into private.vm_feature_policy_audit(actor_id,target_role,feature_key,action,previous_state,next_state)
    values(v_actor,p_role,v_item->>'feature_key','role_rule_saved',v_previous,v_item->>'state');
  end loop;
  return public.vm_admin_feature_matrix(null);
end;
$function$;

create or replace function public.vm_admin_save_user_feature_rules(p_user_id uuid,p_rules jsonb)
returns jsonb
language plpgsql
volatile
security definer
set search_path=''
as $function$
declare v_actor uuid:=(select auth.uid()); v_item jsonb; v_previous text; v_state text;
begin
  if v_actor is null or not (select public.is_admin()) then raise exception 'admin_required' using errcode='42501'; end if;
  if p_user_id is null or p_rules is null or jsonb_typeof(p_rules) is distinct from 'array' or not exists(select 1 from public.profiles where id=p_user_id) then raise exception 'feature_rules_invalid' using errcode='22023'; end if;
  if exists(select 1 from public.profiles where id=p_user_id and role='admin') then raise exception 'admin_policy_immutable' using errcode='22023'; end if;
  for v_item in select value from jsonb_array_elements(p_rules) loop
    v_state:=coalesce(v_item->>'state','inherit');
    if coalesce(v_item->>'feature_key','')='' or v_state not in ('inherit','shown','locked','hidden')
      or not exists(select 1 from private.vm_feature_catalog c where c.feature_key=v_item->>'feature_key' and c.is_delegable) then
      raise exception 'feature_rule_invalid' using errcode='22023';
    end if;
    select state into v_previous from private.vm_feature_user_rules where user_id=p_user_id and feature_key=v_item->>'feature_key';
    if v_state='inherit' then
      delete from private.vm_feature_user_rules where user_id=p_user_id and feature_key=v_item->>'feature_key';
    else
      insert into private.vm_feature_user_rules(user_id,feature_key,state,updated_by,updated_at)
      values(p_user_id,v_item->>'feature_key',v_state,v_actor,now())
      on conflict(user_id,feature_key) do update set state=excluded.state,updated_by=excluded.updated_by,updated_at=excluded.updated_at;
    end if;
    insert into private.vm_feature_policy_audit(actor_id,target_user_id,feature_key,action,previous_state,next_state)
    values(v_actor,p_user_id,v_item->>'feature_key','user_rule_saved',v_previous,nullif(v_state,'inherit'));
  end loop;
  return public.vm_admin_feature_matrix(p_user_id);
end;
$function$;

create or replace function public.vm_admin_deploy_tenant(p_portal_id uuid,p_exam_focus boolean default false)
returns jsonb
language plpgsql
volatile
security definer
set search_path=''
as $function$
declare v_actor uuid:=(select auth.uid()); v_portal public.exam_portals%rowtype;
begin
  if v_actor is null or not (select public.is_admin()) then raise exception 'admin_required' using errcode='42501'; end if;
  select * into v_portal from public.exam_portals where id=p_portal_id for update;
  if v_portal.id is null then raise exception 'tenant_not_found' using errcode='P0002'; end if;
  if v_portal.experience_mode<>'full_site' then raise exception 'tenant_full_site_required' using errcode='22023'; end if;
  if v_portal.brand_id is null or not exists(select 1 from public.brand_templates b where b.id=v_portal.brand_id and b.is_active) then raise exception 'tenant_brand_required' using errcode='22023'; end if;
  if nullif(btrim(v_portal.name),'') is null or nullif(btrim(v_portal.short_name),'') is null or nullif(btrim(v_portal.home_path),'') is null then raise exception 'tenant_incomplete' using errcode='22023'; end if;
  update public.exam_portals set is_active=true,exam_focus_mode=coalesce(p_exam_focus,false),deployed_at=now(),deployed_by=v_actor,updated_at=now() where id=p_portal_id returning * into v_portal;
  insert into public.exam_portal_feature_rules(portal_id,role_scope,feature_key,state,sort_order,updated_by,updated_at)
  values(p_portal_id,'*','exam_focus',case when p_exam_focus then 'shown' else 'hidden' end,-100,v_actor,now())
  on conflict(portal_id,role_scope,feature_key) do update set state=excluded.state,updated_by=excluded.updated_by,updated_at=excluded.updated_at;
  return jsonb_build_object('id',v_portal.id,'slug',v_portal.slug,'is_active',v_portal.is_active,'exam_focus_mode',v_portal.exam_focus_mode,'deployed_at',v_portal.deployed_at);
end;
$function$;

create or replace function public.vm_admin_update_tenant_lifecycle(p_portal_id uuid,p_is_active boolean,p_exam_focus boolean)
returns jsonb
language plpgsql
volatile
security definer
set search_path=''
as $function$
declare v_actor uuid:=(select auth.uid()); v_portal public.exam_portals%rowtype;
begin
  if v_actor is null or not (select public.is_admin()) then raise exception 'admin_required' using errcode='42501'; end if;
  select * into v_portal from public.exam_portals where id=p_portal_id and experience_mode='full_site' for update;
  if v_portal.id is null then raise exception 'tenant_not_found' using errcode='P0002'; end if;
  if coalesce(p_is_active,false) then
    if v_portal.brand_id is null or not exists(select 1 from public.brand_templates b where b.id=v_portal.brand_id and b.is_active) then raise exception 'tenant_brand_required' using errcode='22023'; end if;
    if nullif(btrim(v_portal.name),'') is null or nullif(btrim(v_portal.short_name),'') is null or nullif(btrim(v_portal.home_path),'') is null then raise exception 'tenant_incomplete' using errcode='22023'; end if;
  end if;
  update public.exam_portals set
    is_active=coalesce(p_is_active,false),
    exam_focus_mode=coalesce(p_exam_focus,false),
    deployed_at=case when coalesce(p_is_active,false) then coalesce(deployed_at,now()) else deployed_at end,
    deployed_by=case when coalesce(p_is_active,false) then coalesce(deployed_by,v_actor) else deployed_by end,
    updated_at=now()
  where id=p_portal_id returning * into v_portal;
  insert into public.exam_portal_feature_rules(portal_id,role_scope,feature_key,state,sort_order,updated_by,updated_at)
  values(p_portal_id,'*','exam_focus',case when p_exam_focus then 'shown' else 'hidden' end,-100,v_actor,now())
  on conflict(portal_id,role_scope,feature_key) do update set state=excluded.state,updated_by=excluded.updated_by,updated_at=excluded.updated_at;
  return jsonb_build_object('id',v_portal.id,'is_active',v_portal.is_active,'exam_focus_mode',v_portal.exam_focus_mode,'updated_at',v_portal.updated_at);
end;
$function$;

create or replace function public.vm_bank_delegate_upload_tex(p_document jsonb)
returns jsonb
language plpgsql
volatile
security definer
set search_path=''
as $function$
declare v_uid uuid:=(select auth.uid()); v_raw text:=coalesce(p_document->>'raw_tex',''); v_hash text; v_id uuid; v_stable text; v_status text;
begin
  if v_uid is null or not private.vm_has_feature(v_uid,'question_bank.import_tex') then raise exception 'bank_import_permission_required' using errcode='42501'; end if;
  if p_document is null or jsonb_typeof(p_document) is distinct from 'object' then raise exception 'bank_document_metadata_invalid' using errcode='22023'; end if;
  if octet_length(v_raw) not between 1 and 10000000 then raise exception 'bank_document_size_invalid' using errcode='22023'; end if;
  if jsonb_typeof(coalesce(p_document->'metadata','{}'::jsonb)) is distinct from 'object'
    or jsonb_typeof(coalesce(p_document->'provenance','{}'::jsonb)) is distinct from 'object'
    or octet_length(coalesce(p_document->'metadata','{}'::jsonb)::text)>100000
    or octet_length(coalesce(p_document->'provenance','{}'::jsonb)::text)>100000 then
    raise exception 'bank_document_metadata_invalid' using errcode='22023';
  end if;
  if (select count(*) from private.vm_question_bank_documents d where d.created_by=v_uid and d.created_at>=now()-interval '24 hours')>=100 then
    raise exception 'bank_daily_upload_limit' using errcode='54000';
  end if;
  v_hash:=encode(extensions.digest(convert_to(v_raw,'UTF8'),'sha256'),'hex');
  v_stable:='QBD-'||upper(substr(v_hash,1,24));
  insert into private.vm_question_bank_documents(stable_id,content_hash,source_kind,title,province,exam_year,exam_kind,tags,original_filename,raw_tex,metadata,provenance,status,created_by,updated_at)
  values(v_stable,v_hash,case when p_document->>'source_kind' in ('topic_pack','mock_exam','manual','other') then p_document->>'source_kind' else 'other' end,
    left(coalesce(nullif(p_document->>'title',''),nullif(p_document->>'original_filename',''),'Nguồn TeX chờ duyệt'),240),
    left(nullif(p_document->>'province',''),160),nullif(p_document->>'exam_year','')::integer,left(nullif(p_document->>'exam_kind',''),160),'{}'::text[],left(nullif(p_document->>'original_filename',''),500),v_raw,
    coalesce(p_document->'metadata','{}'::jsonb)||jsonb_build_object('import_state','pending_review','delegated_upload',true),
    coalesce(p_document->'provenance','{}'::jsonb)||jsonb_build_object('uploaded_by',v_uid),
    'quarantined',v_uid,now())
  on conflict(content_hash) do update set updated_at=now()
  returning id,status into v_id,v_status;
  insert into private.vm_feature_policy_audit(actor_id,target_user_id,feature_key,action,details)
  values(v_uid,v_uid,'question_bank.import_tex','delegated_tex_upload',jsonb_build_object('document_id',v_id,'content_hash',v_hash));
  return jsonb_build_object('document_id',v_id,'status',v_status,'pending_review',v_status='quarantined');
exception when invalid_text_representation then
  raise exception 'bank_document_metadata_invalid' using errcode='22023';
end;
$function$;

create or replace function public.vm_bank_download_tex(p_document_id uuid)
returns jsonb
language plpgsql
volatile
security definer
set search_path=''
as $function$
declare v_uid uuid:=(select auth.uid()); v_result jsonb;
begin
  if v_uid is null or not private.vm_has_feature(v_uid,'question_bank.download_tex') then raise exception 'bank_download_permission_required' using errcode='42501'; end if;
  select jsonb_build_object('id',d.id,'title',d.title,'original_filename',d.original_filename,'raw_tex',d.raw_tex,'source_kind',d.source_kind,'updated_at',d.updated_at)
  into v_result from private.vm_question_bank_documents d where d.id=p_document_id and d.status<>'archived';
  if v_result is null then raise exception 'bank_document_not_found' using errcode='P0002'; end if;
  insert into private.vm_feature_policy_audit(actor_id,target_user_id,feature_key,action,details)
  values(v_uid,v_uid,'question_bank.download_tex','tex_download',jsonb_build_object('document_id',p_document_id));
  return v_result;
end;
$function$;

revoke all on function public.vm_my_feature_access(uuid) from public,anon;
revoke all on function public.vm_my_bank_capabilities() from public,anon;
revoke all on function public.vm_admin_feature_matrix(uuid) from public,anon;
revoke all on function public.vm_admin_save_role_feature_rules(text,jsonb) from public,anon;
revoke all on function public.vm_admin_save_user_feature_rules(uuid,jsonb) from public,anon;
revoke all on function public.vm_admin_deploy_tenant(uuid,boolean) from public,anon;
revoke all on function public.vm_admin_update_tenant_lifecycle(uuid,boolean,boolean) from public,anon;
revoke all on function public.vm_bank_delegate_upload_tex(jsonb) from public,anon;
revoke all on function public.vm_bank_download_tex(uuid) from public,anon;
grant execute on function public.vm_my_feature_access(uuid) to authenticated;
grant execute on function public.vm_my_bank_capabilities() to authenticated;
grant execute on function public.vm_admin_feature_matrix(uuid) to authenticated;
grant execute on function public.vm_admin_save_role_feature_rules(text,jsonb) to authenticated;
grant execute on function public.vm_admin_save_user_feature_rules(uuid,jsonb) to authenticated;
grant execute on function public.vm_admin_deploy_tenant(uuid,boolean) to authenticated;
grant execute on function public.vm_admin_update_tenant_lifecycle(uuid,boolean,boolean) to authenticated;
grant execute on function public.vm_bank_delegate_upload_tex(jsonb) to authenticated;
grant execute on function public.vm_bank_download_tex(uuid) to authenticated;
